import errno
import os
import pathlib
import posixpath
import secrets
import stat
import unicodedata
from collections.abc import Mapping
from dataclasses import dataclass


GENERATED_SWIFT_HEADER = "// Generated by Petrel. DO NOT EDIT.\n"
_GENERATED_SWIFT_HEADER_BYTES = GENERATED_SWIFT_HEADER.encode("utf-8")

_CLOSE_ON_EXEC = getattr(os, "O_CLOEXEC", 0)
_NO_FOLLOW = getattr(os, "O_NOFOLLOW", 0)
_DIRECTORY_FLAGS = os.O_RDONLY | os.O_DIRECTORY | _NO_FOLLOW | _CLOSE_ON_EXEC
_READ_FLAGS = os.O_RDONLY | _NO_FOLLOW | _CLOSE_ON_EXEC
_TEMP_FLAGS = os.O_RDWR | os.O_CREAT | os.O_EXCL | _NO_FOLLOW | _CLOSE_ON_EXEC


@dataclass(frozen=True)
class _Node:
    mode: int
    device: int
    inode: int
    link_count: int
    size: int
    mtime_ns: int
    ctime_ns: int


@dataclass(frozen=True)
class _ExpectedFile:
    relative_path: pathlib.PurePosixPath
    payload: bytes


@dataclass(frozen=True)
class _ExistingFile:
    node: _Node
    content: bytes


@dataclass(frozen=True)
class _StaleFile:
    relative_path: pathlib.PurePosixPath
    node: _Node


def _node_from_stat(value: os.stat_result) -> _Node:
    return _Node(
        mode=value.st_mode,
        device=value.st_dev,
        inode=value.st_ino,
        link_count=value.st_nlink,
        size=value.st_size,
        mtime_ns=value.st_mtime_ns,
        ctime_ns=value.st_ctime_ns,
    )


def _same_object(left: _Node, right: _Node) -> bool:
    return (
        left.device,
        left.inode,
        stat.S_IFMT(left.mode),
    ) == (
        right.device,
        right.inode,
        stat.S_IFMT(right.mode),
    )


def _same_file_snapshot(left: _Node, right: _Node) -> bool:
    return (
        left.mode,
        left.device,
        left.inode,
        left.link_count,
        left.size,
        left.mtime_ns,
        left.ctime_ns,
    ) == (
        right.mode,
        right.device,
        right.inode,
        right.link_count,
        right.size,
        right.mtime_ns,
        right.ctime_ns,
    )


def _alias_key(component: str) -> str:
    normalized = unicodedata.normalize("NFC", component)
    return unicodedata.normalize("NFC", normalized.casefold())


def _validated_projection(
    output_root: str,
    expected_files: Mapping[str, str],
) -> tuple[pathlib.Path, dict[str, _ExpectedFile]]:
    """Validate the complete logical projection without filesystem mutation."""
    try:
        root_value = os.fspath(output_root)
    except TypeError as error:
        raise ValueError("output root must be a filesystem path") from error
    if not isinstance(root_value, str) or not root_value:
        raise ValueError("output root path must be a non-empty string")
    root = pathlib.Path(root_value).absolute()

    try:
        items = tuple(expected_files.items())
    except (AttributeError, TypeError) as error:
        raise ValueError("expected files must be a mapping of relative paths") from error

    trie = {"file": False, "children": {}}
    validated: dict[str, _ExpectedFile] = {}
    for raw_path, raw_content in items:
        if not isinstance(raw_path, str) or not raw_path:
            raise ValueError("generated target path must be a non-empty relative string")
        if "\x00" in raw_path:
            raise ValueError(f"generated target path contains NUL: {raw_path!r}")
        if "\\" in raw_path:
            raise ValueError(
                f"generated target path must use normalized POSIX separators: {raw_path!r}"
            )

        relative = pathlib.PurePosixPath(raw_path)
        if relative.is_absolute():
            raise ValueError(f"generated target path must be relative: {raw_path!r}")
        normalized = posixpath.normpath(raw_path)
        if normalized in ("", ".", "..") or normalized.startswith("../"):
            raise ValueError(f"generated target path escapes its output root: {raw_path!r}")
        if normalized != raw_path:
            raise ValueError(
                f"generated target path must already be normalized: {raw_path!r}"
            )
        if not raw_path.endswith(".swift"):
            raise ValueError(
                f"generated target must end in lowercase .swift: {raw_path!r}"
            )
        if not isinstance(raw_content, str):
            raise ValueError(f"generated target content must be text: {raw_path!r}")

        trie_node = trie
        for component in relative.parts:
            if trie_node["file"]:
                raise ValueError(
                    f"generated target has a file ancestor structural conflict: {raw_path!r}"
                )
            alias = _alias_key(component)
            child = trie_node["children"].get(alias)
            if child is None:
                child = (component, {"file": False, "children": {}})
                trie_node["children"][alias] = child
            elif child[0] != component:
                raise ValueError(
                    "generated target component aliases another case or Unicode "
                    f"spelling: {component!r} versus {child[0]!r}"
                )
            trie_node = child[1]

        if trie_node["file"]:
            raise ValueError(f"generated target collision after normalization: {raw_path!r}")
        if trie_node["children"]:
            raise ValueError(
                f"generated target is an ancestor of another target: {raw_path!r}"
            )
        trie_node["file"] = True

        content = raw_content
        while content.startswith(GENERATED_SWIFT_HEADER):
            content = content[len(GENERATED_SWIFT_HEADER):]
        payload = (GENERATED_SWIFT_HEADER + content).encode("utf-8")
        validated[normalized] = _ExpectedFile(relative, payload)

    return root, validated


def _open_root(root: pathlib.Path) -> tuple[int, _Node]:
    try:
        before = _node_from_stat(os.lstat(root))
    except FileNotFoundError:
        try:
            root.mkdir(parents=True, exist_ok=False)
        except OSError as error:
            raise ValueError(f"unable to create output root directory: {root}") from error
        before = _node_from_stat(os.lstat(root))

    if stat.S_ISLNK(before.mode):
        raise ValueError(f"output root must not be a symlink: {root}")
    if not stat.S_ISDIR(before.mode):
        raise ValueError(f"output root must be a directory: {root}")

    try:
        root_fd = os.open(root, _DIRECTORY_FLAGS)
    except OSError as error:
        raise ValueError(f"unable to open output root without following links: {root}") from error
    try:
        opened = _node_from_stat(os.fstat(root_fd))
        if not stat.S_ISDIR(opened.mode) or not _same_object(before, opened):
            raise ValueError("output root identity changed while it was opened")
    except BaseException:
        os.close(root_fd)
        raise
    return root_fd, opened


def _lstat_at(parent_fd: int, name: str) -> _Node | None:
    try:
        return _node_from_stat(os.stat(name, dir_fd=parent_fd, follow_symlinks=False))
    except FileNotFoundError:
        return None


def _open_directory_at(parent_fd: int, name: str, expected: _Node) -> int:
    try:
        directory_fd = os.open(name, _DIRECTORY_FLAGS, dir_fd=parent_fd)
    except OSError as error:
        raise ValueError(f"expected ancestor is not a no-follow directory: {name!r}") from error
    try:
        opened = _node_from_stat(os.fstat(directory_fd))
        if not stat.S_ISDIR(opened.mode) or not _same_object(expected, opened):
            raise ValueError(f"expected ancestor directory identity changed: {name!r}")
    except BaseException:
        os.close(directory_fd)
        raise
    return directory_fd


def _directory_aliases(names: list[str], context: str) -> dict[str, str]:
    aliases: dict[str, str] = {}
    for name in names:
        alias = _alias_key(name)
        previous = aliases.get(alias)
        if previous is not None and previous != name:
            raise ValueError(
                f"filesystem contains ambiguous case or Unicode aliases in {context}: "
                f"{previous!r} and {name!r}"
            )
        aliases[alias] = name
    return aliases


def _scan_tree(
    root_fd: int,
    root_node: _Node,
) -> tuple[
    dict[tuple[str, ...], dict[str, _Node]],
    dict[tuple[str, ...], dict[str, str]],
    dict[tuple[str, ...], _Node],
]:
    entries: dict[tuple[str, ...], dict[str, _Node]] = {}
    aliases: dict[tuple[str, ...], dict[str, str]] = {}
    directories: dict[tuple[str, ...], _Node] = {(): root_node}

    def visit(parts: tuple[str, ...], directory_fd: int) -> None:
        try:
            names = sorted(os.listdir(directory_fd))
        except OSError as error:
            raise ValueError(f"unable to inspect projection directory: {'/'.join(parts)}") from error
        aliases[parts] = _directory_aliases(names, "/".join(parts) or ".")
        directory_entries: dict[str, _Node] = {}
        for name in names:
            node = _lstat_at(directory_fd, name)
            if node is None:
                raise ValueError(f"filesystem entry changed during preflight: {name!r}")
            directory_entries[name] = node
        entries[parts] = directory_entries

        for name, node in directory_entries.items():
            if not stat.S_ISDIR(node.mode):
                continue
            child_fd = _open_directory_at(directory_fd, name, node)
            child_parts = parts + (name,)
            directories[child_parts] = node
            try:
                visit(child_parts, child_fd)
            finally:
                os.close(child_fd)

    visit((), root_fd)
    return entries, aliases, directories


def _open_relative_directory(
    root_fd: int,
    parts: tuple[str, ...],
    directories: Mapping[tuple[str, ...], _Node],
) -> int:
    current_fd = os.dup(root_fd)
    current_parts: tuple[str, ...] = ()
    try:
        for component in parts:
            current_parts += (component,)
            expected = directories.get(current_parts)
            if expected is None:
                raise ValueError(
                    f"projection ancestor was not preflighted: {'/'.join(current_parts)}"
                )
            next_fd = _open_directory_at(current_fd, component, expected)
            os.close(current_fd)
            current_fd = next_fd
        return current_fd
    except Exception:
        os.close(current_fd)
        raise


def _read_regular_file_at(
    parent_fd: int,
    name: str,
    expected: _Node,
    context: str,
) -> bytes:
    try:
        file_fd = os.open(name, _READ_FLAGS, dir_fd=parent_fd)
    except OSError as error:
        raise ValueError(f"unable to inspect {context} without following links") from error
    try:
        opened_before = _node_from_stat(os.fstat(file_fd))
        if (
            not stat.S_ISREG(opened_before.mode)
            or not _same_file_snapshot(expected, opened_before)
        ):
            raise ValueError(f"{context} identity changed during preflight")
        chunks = []
        while True:
            chunk = os.read(file_fd, 64 * 1024)
            if not chunk:
                break
            chunks.append(chunk)
        opened_after = _node_from_stat(os.fstat(file_fd))
        if (
            not _same_file_snapshot(opened_before, opened_after)
            or not _same_file_snapshot(expected, opened_after)
        ):
            raise ValueError(f"{context} snapshot changed while it was read")
        return b"".join(chunks)
    finally:
        os.close(file_fd)


def _preflight_expected_files(
    root_fd: int,
    expected_files: Mapping[str, _ExpectedFile],
    entries: Mapping[tuple[str, ...], Mapping[str, _Node]],
    aliases: Mapping[tuple[str, ...], Mapping[str, str]],
    directories: Mapping[tuple[str, ...], _Node],
) -> dict[str, _ExistingFile]:
    existing_files: dict[str, _ExistingFile] = {}
    inode_owners: dict[tuple[int, int], str] = {}

    for relative_path, expected in sorted(expected_files.items()):
        parts = expected.relative_path.parts
        parent_parts: tuple[str, ...] = ()
        missing_ancestor = False
        for component in parts[:-1]:
            actual = aliases[parent_parts].get(_alias_key(component))
            if actual is None:
                missing_ancestor = True
                break
            if actual != component:
                raise ValueError(
                    f"expected ancestor aliases existing filesystem spelling: "
                    f"{component!r} versus {actual!r}"
                )
            node = entries[parent_parts][actual]
            if stat.S_ISLNK(node.mode):
                raise ValueError(f"expected ancestor must not be a symlink: {relative_path}")
            if not stat.S_ISDIR(node.mode):
                raise ValueError(f"expected ancestor is not a directory: {relative_path}")
            parent_parts += (component,)

        if missing_ancestor:
            continue

        leaf = parts[-1]
        actual = aliases[parent_parts].get(_alias_key(leaf))
        if actual is None:
            continue
        if actual != leaf:
            raise ValueError(
                f"expected target aliases existing filesystem spelling: "
                f"{leaf!r} versus {actual!r}"
            )
        node = entries[parent_parts][actual]
        if stat.S_ISLNK(node.mode):
            raise ValueError(f"expected target must not be a symlink: {relative_path}")
        if not stat.S_ISREG(node.mode):
            raise ValueError(f"expected target must be a regular file: {relative_path}")
        if node.link_count != 1:
            raise ValueError(f"expected target has ambiguous hardlink link count: {relative_path}")
        inode = (node.device, node.inode)
        previous = inode_owners.get(inode)
        if previous is not None:
            raise ValueError(
                f"expected targets share one existing inode: {previous!r} and {relative_path!r}"
            )
        inode_owners[inode] = relative_path

        parent_fd = _open_relative_directory(root_fd, parent_parts, directories)
        try:
            content = _read_regular_file_at(
                parent_fd,
                leaf,
                node,
                f"expected target {relative_path}",
            )
            after_read = _lstat_at(parent_fd, leaf)
            if after_read is None or not _same_file_snapshot(node, after_read):
                raise ValueError(
                    f"expected target {relative_path} snapshot changed after preflight read"
                )
        finally:
            os.close(parent_fd)
        existing_files[relative_path] = _ExistingFile(node, content)

    return existing_files


def _preflight_stale_files(
    root_fd: int,
    expected_files: Mapping[str, _ExpectedFile],
    entries: Mapping[tuple[str, ...], Mapping[str, _Node]],
    directories: Mapping[tuple[str, ...], _Node],
) -> list[_StaleFile]:
    stale_files = []
    expected_paths = set(expected_files)
    for parent_parts, directory_entries in entries.items():
        for name, node in directory_entries.items():
            if not name.endswith(".swift") or not stat.S_ISREG(node.mode):
                continue
            relative = pathlib.PurePosixPath(*parent_parts, name)
            if relative.as_posix() in expected_paths:
                continue
            parent_fd = _open_relative_directory(root_fd, parent_parts, directories)
            try:
                content = _read_regular_file_at(
                    parent_fd,
                    name,
                    node,
                    f"unexpected Swift file {relative.as_posix()}",
                )
                after_read = _lstat_at(parent_fd, name)
                if after_read is None or not _same_file_snapshot(node, after_read):
                    raise ValueError(
                        f"unexpected Swift file {relative} snapshot changed after preflight read"
                    )
            finally:
                os.close(parent_fd)
            if not content.startswith(_GENERATED_SWIFT_HEADER_BYTES):
                continue
            if node.link_count != 1:
                raise ValueError(
                    f"owned stale Swift file has ambiguous hardlink link count: {relative}"
                )
            stale_files.append(_StaleFile(relative, node))
    return stale_files


def _live_aliases(directory_fd: int, context: str) -> dict[str, str]:
    try:
        names = os.listdir(directory_fd)
    except OSError as error:
        raise ValueError(f"unable to inspect projection directory: {context}") from error
    return _directory_aliases(names, context)


def _ensure_expected_directories(
    root_fd: int,
    expected_files: Mapping[str, _ExpectedFile],
    directories: dict[tuple[str, ...], _Node],
) -> None:
    for expected in sorted(expected_files.values(), key=lambda item: item.relative_path.as_posix()):
        current_fd = os.dup(root_fd)
        current_parts: tuple[str, ...] = ()
        try:
            for component in expected.relative_path.parts[:-1]:
                next_parts = current_parts + (component,)
                known = directories.get(next_parts)
                if known is None:
                    actual = _live_aliases(current_fd, "/".join(current_parts) or ".").get(
                        _alias_key(component)
                    )
                    if actual is not None:
                        raise ValueError(
                            f"expected ancestor appeared after preflight: {component!r}"
                        )
                    try:
                        os.mkdir(component, 0o777, dir_fd=current_fd)
                    except OSError as error:
                        raise ValueError(
                            f"unable to create expected projection ancestor: {component!r}"
                        ) from error
                    created = _lstat_at(current_fd, component)
                    if created is None or not stat.S_ISDIR(created.mode):
                        raise ValueError(
                            f"created projection ancestor is not a directory: {component!r}"
                        )
                    known = created
                    directories[next_parts] = created
                next_fd = _open_directory_at(current_fd, component, known)
                os.close(current_fd)
                current_fd = next_fd
                current_parts = next_parts
        finally:
            os.close(current_fd)


def _assert_root_identity(root: pathlib.Path, expected: _Node) -> None:
    try:
        current = _node_from_stat(os.lstat(root))
    except FileNotFoundError as error:
        raise ValueError("output root identity changed or disappeared") from error
    if (
        stat.S_ISLNK(current.mode)
        or not stat.S_ISDIR(current.mode)
        or not _same_object(expected, current)
    ):
        raise ValueError("output root identity changed during projection publication")


def _revalidate_destination(
    parent_fd: int,
    leaf: str,
    relative_path: pathlib.PurePosixPath,
    existing: _ExistingFile | None,
) -> None:
    aliases = _live_aliases(parent_fd, relative_path.parent.as_posix())
    actual = aliases.get(_alias_key(leaf))
    if existing is None:
        if actual is not None:
            raise ValueError(f"expected target appeared after preflight: {relative_path}")
        return
    if actual != leaf:
        raise ValueError(f"expected target spelling changed after preflight: {relative_path}")
    current = _lstat_at(parent_fd, leaf)
    if (
        current is None
        or not stat.S_ISREG(current.mode)
        or current.link_count != 1
        or not _same_file_snapshot(existing.node, current)
    ):
        raise ValueError(f"expected target identity changed after preflight: {relative_path}")


def _read_open_file(file_fd: int) -> bytes:
    os.lseek(file_fd, 0, os.SEEK_SET)
    chunks = []
    while True:
        chunk = os.read(file_fd, 64 * 1024)
        if not chunk:
            return b"".join(chunks)
        chunks.append(chunk)


def _cleanup_temporary_name(
    parent_fd: int,
    temporary_name: str,
    retained_node: _Node | None,
) -> None:
    current = _lstat_at(parent_fd, temporary_name)
    if current is None:
        return
    if stat.S_ISLNK(current.mode):
        os.unlink(temporary_name, dir_fd=parent_fd)
        return
    if retained_node is not None and _same_object(current, retained_node):
        os.unlink(temporary_name, dir_fd=parent_fd)


def _write_bytes(
    relative_path: pathlib.PurePosixPath,
    root_fd: int,
    directories: Mapping[tuple[str, ...], _Node],
    payload: bytes,
    existing: _ExistingFile | None,
) -> None:
    """Synchronously install one target through fresh root-anchored walks."""
    parent_parts = relative_path.parts[:-1]
    leaf = relative_path.parts[-1]
    parent_fd = _open_relative_directory(root_fd, parent_parts, directories)
    temporary_name = None
    temporary_fd = None
    retained_node = None
    installed_node = None
    try:
        for _ in range(100):
            candidate = f".petrel-projection-{secrets.token_hex(12)}.tmp"
            try:
                temporary_fd = os.open(candidate, _TEMP_FLAGS, 0o666, dir_fd=parent_fd)
                temporary_name = candidate
                break
            except FileExistsError:
                continue
        if temporary_fd is None or temporary_name is None:
            raise ValueError(f"unable to allocate projection temporary for {relative_path}")

        retained_node = _node_from_stat(os.fstat(temporary_fd))
        if not stat.S_ISREG(retained_node.mode) or retained_node.link_count != 1:
            raise ValueError(f"projection temporary is not an owned regular file: {relative_path}")
        remaining = memoryview(payload)
        while remaining:
            written = os.write(temporary_fd, remaining)
            if written <= 0:
                raise OSError(errno.EIO, "short projection write")
            remaining = remaining[written:]
        if existing is not None:
            os.fchmod(temporary_fd, stat.S_IMODE(existing.node.mode))
        os.fsync(temporary_fd)
        retained_node = _node_from_stat(os.fstat(temporary_fd))
        if (
            not stat.S_ISREG(retained_node.mode)
            or retained_node.link_count != 1
            or retained_node.size != len(payload)
        ):
            raise ValueError(f"projection temporary changed while writing: {relative_path}")

        _revalidate_destination(parent_fd, leaf, relative_path, existing)
        source_node = _lstat_at(parent_fd, temporary_name)
        retained_before_install = _node_from_stat(os.fstat(temporary_fd))
        if (
            source_node is None
            or not stat.S_ISREG(source_node.mode)
            or source_node.link_count != 1
            or not _same_file_snapshot(source_node, retained_before_install)
        ):
            raise ValueError(
                f"projection temporary source identity changed before install: {relative_path}"
            )

        os.replace(
            temporary_name,
            leaf,
            src_dir_fd=parent_fd,
            dst_dir_fd=parent_fd,
        )
        installed_node = _node_from_stat(os.fstat(temporary_fd))
        installed_name = _lstat_at(parent_fd, leaf)
        if (
            installed_name is None
            or not stat.S_ISREG(installed_name.mode)
            or installed_name.link_count != 1
            or not _same_file_snapshot(installed_name, installed_node)
        ):
            raise ValueError(
                f"installed projection target does not match retained temporary: {relative_path}"
            )
        retained_content = _read_open_file(temporary_fd)
        retained_after_read = _node_from_stat(os.fstat(temporary_fd))
        installed_after_read = _lstat_at(parent_fd, leaf)
        if (
            retained_content != payload
            or installed_after_read is None
            or not _same_file_snapshot(installed_node, retained_after_read)
            or not _same_file_snapshot(retained_after_read, installed_after_read)
        ):
            raise ValueError(
                f"installed projection target content or identity changed: {relative_path}"
            )
        installed_node = retained_after_read
    finally:
        try:
            if temporary_name is not None:
                _cleanup_temporary_name(parent_fd, temporary_name, retained_node)
        finally:
            try:
                if temporary_fd is not None:
                    os.close(temporary_fd)
            finally:
                os.close(parent_fd)

    reachable_parent_fd = _open_relative_directory(root_fd, parent_parts, directories)
    try:
        reachable = _lstat_at(reachable_parent_fd, leaf)
        if (
            installed_node is None
            or reachable is None
            or not _same_file_snapshot(installed_node, reachable)
        ):
            raise ValueError(
                f"installed projection target is no longer reachable from root: {relative_path}"
            )
        reachable_content = _read_regular_file_at(
            reachable_parent_fd,
            leaf,
            reachable,
            f"installed projection target {relative_path}",
        )
        reachable_after_read = _lstat_at(reachable_parent_fd, leaf)
        if (
            reachable_content != payload
            or reachable_after_read is None
            or not _same_file_snapshot(reachable, reachable_after_read)
        ):
            raise ValueError(
                f"installed projection target changed after root reachability check: {relative_path}"
            )
    finally:
        os.close(reachable_parent_fd)


def _same_file_across_rename(before: _Node, after: _Node) -> bool:
    return (
        before.mode,
        before.device,
        before.inode,
        before.link_count,
        before.size,
        before.mtime_ns,
    ) == (
        after.mode,
        after.device,
        after.inode,
        after.link_count,
        after.size,
        after.mtime_ns,
    ) and after.ctime_ns >= before.ctime_ns


def _open_quarantine(root_fd: int) -> tuple[str, int]:
    for _ in range(100):
        name = f".petrel-projection-quarantine-{secrets.token_hex(12)}"
        created = None
        quarantine_fd = None
        try:
            os.mkdir(name, 0o700, dir_fd=root_fd)
        except FileExistsError:
            continue
        try:
            created = _lstat_at(root_fd, name)
            if created is None or not stat.S_ISDIR(created.mode):
                raise ValueError("projection quarantine was not created as a directory")
            quarantine_fd = _open_directory_at(root_fd, name, created)
            os.fchmod(quarantine_fd, 0o700)
            opened = _node_from_stat(os.fstat(quarantine_fd))
            if not stat.S_ISDIR(opened.mode) or stat.S_IMODE(opened.mode) != 0o700:
                raise ValueError("projection quarantine is not an owned 0700 directory")
            return name, quarantine_fd
        except BaseException:
            if quarantine_fd is not None:
                try:
                    os.close(quarantine_fd)
                except OSError:
                    pass
            if created is not None:
                current = _lstat_at(root_fd, name)
                if (
                    current is not None
                    and stat.S_ISDIR(current.mode)
                    and _same_object(created, current)
                ):
                    try:
                        os.rmdir(name, dir_fd=root_fd)
                    except OSError:
                        pass
            raise
    raise ValueError("unable to allocate projection quarantine directory")


def _restore_quarantined_name(
    parent_fd: int,
    leaf: str,
    quarantine_fd: int,
    slot: str,
) -> None:
    quarantined = _lstat_at(quarantine_fd, slot)
    if quarantined is None or _lstat_at(parent_fd, leaf) is not None:
        return
    os.rename(
        slot,
        leaf,
        src_dir_fd=quarantine_fd,
        dst_dir_fd=parent_fd,
    )


def _delete_stale_files(
    root_fd: int,
    stale_files: list[_StaleFile],
    directories: Mapping[tuple[str, ...], _Node],
) -> None:
    if not stale_files:
        return
    quarantine_name, quarantine_fd = _open_quarantine(root_fd)
    try:
        for stale in sorted(stale_files, key=lambda item: item.relative_path.as_posix()):
            parent_parts = stale.relative_path.parts[:-1]
            leaf = stale.relative_path.parts[-1]
            parent_fd = _open_relative_directory(root_fd, parent_parts, directories)
            slot = f"stale-{secrets.token_hex(12)}"
            retained_fd = None
            quarantined = False
            try:
                current = _lstat_at(parent_fd, leaf)
                if (
                    current is None
                    or not stat.S_ISREG(current.mode)
                    or current.link_count != 1
                    or not _same_file_snapshot(stale.node, current)
                ):
                    raise ValueError(
                        f"owned stale Swift identity changed before quarantine: {stale.relative_path}"
                    )
                os.rename(
                    leaf,
                    slot,
                    src_dir_fd=parent_fd,
                    dst_dir_fd=quarantine_fd,
                )
                quarantined = True
                quarantine_snapshot = _lstat_at(quarantine_fd, slot)
                if (
                    quarantine_snapshot is None
                    or not stat.S_ISREG(quarantine_snapshot.mode)
                    or quarantine_snapshot.link_count != 1
                    or not _same_file_across_rename(stale.node, quarantine_snapshot)
                ):
                    raise ValueError(
                        f"owned stale Swift changed while entering quarantine: {stale.relative_path}"
                    )
                retained_fd = os.open(slot, _READ_FLAGS, dir_fd=quarantine_fd)
                retained_before_read = _node_from_stat(os.fstat(retained_fd))
                if not _same_file_snapshot(quarantine_snapshot, retained_before_read):
                    raise ValueError(
                        f"owned stale Swift quarantine identity changed: {stale.relative_path}"
                    )
                content = _read_regular_file_at(
                    quarantine_fd,
                    slot,
                    retained_before_read,
                    f"owned stale Swift file {stale.relative_path}",
                )
                retained_after_read = _node_from_stat(os.fstat(retained_fd))
                named_after_read = _lstat_at(quarantine_fd, slot)
                if (
                    not content.startswith(_GENERATED_SWIFT_HEADER_BYTES)
                    or named_after_read is None
                    or not _same_file_snapshot(retained_before_read, retained_after_read)
                    or not _same_file_snapshot(retained_after_read, named_after_read)
                ):
                    raise ValueError(
                        f"owned stale Swift content or snapshot changed in quarantine: {stale.relative_path}"
                    )
                os.unlink(slot, dir_fd=quarantine_fd)
                quarantined = False
            except Exception:
                if quarantined:
                    _restore_quarantined_name(
                        parent_fd,
                        leaf,
                        quarantine_fd,
                        slot,
                    )
                raise
            finally:
                try:
                    if retained_fd is not None:
                        os.close(retained_fd)
                finally:
                    os.close(parent_fd)
    finally:
        try:
            os.close(quarantine_fd)
        finally:
            try:
                os.rmdir(quarantine_name, dir_fd=root_fd)
            except OSError:
                pass


async def write_swift_projection(
    output_root: str,
    expected_files: Mapping[str, str],
) -> None:
    """Publish one closed generated-Swift projection without following links.

    Publication assumes exclusive generation ownership. An uncooperative concurrent writer
    with parent-directory write authority can still race a final POSIX name
    mutation; synchronous transactions and before/after checks narrow that external-
    writer race and fail closed, but do not claim mathematical race freedom.
    """
    root, validated = _validated_projection(output_root, expected_files)
    root_fd, root_node = _open_root(root)
    try:
        entries, aliases, directories = _scan_tree(root_fd, root_node)
        existing_files = _preflight_expected_files(
            root_fd,
            validated,
            entries,
            aliases,
            directories,
        )
        stale_files = _preflight_stale_files(
            root_fd,
            validated,
            entries,
            directories,
        )
        _ensure_expected_directories(root_fd, validated, directories)
        _assert_root_identity(root, root_node)

        for relative_path, expected in sorted(validated.items()):
            existing = existing_files.get(relative_path)
            if existing is not None and existing.content == expected.payload:
                parent_parts = expected.relative_path.parts[:-1]
                parent_fd = _open_relative_directory(root_fd, parent_parts, directories)
                try:
                    leaf = expected.relative_path.parts[-1]
                    aliases = _live_aliases(parent_fd, expected.relative_path.parent.as_posix())
                    if aliases.get(_alias_key(leaf)) != leaf:
                        raise ValueError(
                            f"expected target spelling changed after preflight: {relative_path}"
                        )
                    live_node = _lstat_at(parent_fd, leaf)
                    if (
                        live_node is None
                        or not stat.S_ISREG(live_node.mode)
                        or live_node.link_count != 1
                        or not _same_object(existing.node, live_node)
                    ):
                        raise ValueError(
                            f"expected target identity changed after preflight: {relative_path}"
                        )
                    live_content = _read_regular_file_at(
                        parent_fd,
                        leaf,
                        live_node,
                        f"expected target {relative_path}",
                    )
                    live_after_read = _lstat_at(parent_fd, leaf)
                    if (
                        live_after_read is None
                        or not _same_file_snapshot(live_node, live_after_read)
                    ):
                        raise ValueError(
                            f"expected target {relative_path} snapshot changed after final read"
                        )
                    if live_content == expected.payload:
                        continue
                    existing = _ExistingFile(live_after_read, live_content)
                finally:
                    os.close(parent_fd)
            _write_bytes(
                expected.relative_path,
                root_fd,
                directories,
                expected.payload,
                existing,
            )
            _assert_root_identity(root, root_node)

        _assert_root_identity(root, root_node)
        _delete_stale_files(root_fd, stale_files, directories)
        _assert_root_identity(root, root_node)
    finally:
        os.close(root_fd)
