import Foundation

public struct DeviceRecord: Sendable, Equatable {
  public var firstSeen: Date
  public var lastSeen: Date
  public var requestCount: Int
}

/// Per-device (`jkt`) usage tracking and refusal policy — the backend's
/// veto power from the proposal. Implementations may persist; the protocol
/// is the seam for a future SQLite-backed store.
public protocol DeviceStore: Sendable {
  func record(jkt: String, now: Date) async
  func isDenied(jkt: String) async -> Bool
  func snapshot() async -> [String: DeviceRecord]
}

public actor InMemoryDeviceStore: DeviceStore {
  // Pragmatic bound for the in-memory default store: `jkt` is generated by
  // the caller's own device key, so a key-rotating attacker could otherwise
  // grow this dict without bound (one entry per jkt ever seen) and OOM the
  // process. A real deployment that needs unbounded device history should
  // use a SQLite-backed store instead — this is just a memory safety valve
  // for the zero-dependency default.
  private static let capacity = 10_000

  private var devices: [String: DeviceRecord] = [:]
  private let deniedJKTs: Set<String>

  public init(deniedJKTs: [String]) {
    self.deniedJKTs = Set(deniedJKTs)
  }

  public func record(jkt: String, now: Date) {
    if var record = devices[jkt] {
      record.lastSeen = now
      record.requestCount += 1
      devices[jkt] = record
    } else {
      if devices.count >= Self.capacity,
         let oldest = devices.min(by: { $0.value.lastSeen < $1.value.lastSeen })?.key
      {
        devices.removeValue(forKey: oldest)
      }
      devices[jkt] = DeviceRecord(firstSeen: now, lastSeen: now, requestCount: 1)
    }
  }

  public func isDenied(jkt: String) -> Bool {
    deniedJKTs.contains(jkt)
  }

  public func snapshot() -> [String: DeviceRecord] {
    devices
  }
}
