import collections.abc
import asyncio
import errno
import json
import os
import pathlib
import re
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile
import unicodedata
import unittest
from unittest import mock


GENERATOR_DIR = pathlib.Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = GENERATOR_DIR.parent
sys.path.insert(0, str(GENERATOR_DIR))

EXPECTED_HEADER = "// Generated by Petrel. DO NOT EDIT.\n"
_SHELL_ASSIGNMENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")
_FORBIDDEN_AMBIENT_EXECUTABLES = {
    "brew",
    "mint",
    "open",
    "osascript",
    "pip",
    "pip3",
    "python",
    "python3",
    "swift",
    "swiftformat",
    "xcodebuild",
    "xcrun",
}
_ARITHMETIC_EXPANSION = re.compile(r"\$\(\((?:[^()]|\([^()]*\))*\)\)")
_FORBIDDEN_AMBIENT_TOKEN = re.compile(
    r"(?<![A-Za-z0-9_.-])(" 
    + "|".join(
        re.escape(executable)
        for executable in sorted(_FORBIDDEN_AMBIENT_EXECUTABLES, key=len, reverse=True)
    )
    + r")(?![A-Za-z0-9_.-])"
)
_DYNAMIC_SHELL_DISPATCHERS = {
    "bash",
    "command",
    "env",
    "eval",
    "exec",
    "find",
    "nice",
    "nohup",
    "sh",
    "sudo",
    "timeout",
    "xargs",
    "zsh",
}
_DYNAMIC_SHELL_DISPATCHER_TOKEN = re.compile(
    r"(?<![A-Za-z0-9_.-])(" 
    + "|".join(
        re.escape(executable)
        for executable in sorted(_DYNAMIC_SHELL_DISPATCHERS, key=len, reverse=True)
    )
    + r")(?![A-Za-z0-9_.-])"
)
_APPROVED_DYNAMIC_EXECUTABLES = {"$PETREL_PYTHON", "$RELEASE_MINT"}


def _segment_executables(tokens):
    index = 0
    while index < len(tokens) and tokens[index] in {
        "!",
        "do",
        "elif",
        "else",
        "if",
        "then",
        "time",
        "until",
        "while",
        "{",
    }:
        index += 1
    while index < len(tokens):
        while index < len(tokens) and _SHELL_ASSIGNMENT.match(tokens[index]):
            index += 1
        if index >= len(tokens):
            return ()
        executable = pathlib.PurePosixPath(tokens[index]).name
        if executable == "env":
            index += 1
            while index < len(tokens):
                option = tokens[index]
                if option in {"-u", "--unset"}:
                    index += 2
                elif option.startswith("--unset="):
                    index += 1
                elif option == "--":
                    index += 1
                    break
                elif option.startswith("-"):
                    index += 1
                else:
                    break
            continue
        if executable in {"command", "sudo"}:
            index += 1
            while index < len(tokens) and tokens[index].startswith("-"):
                index += 1
            continue
        results = [executable]
        arguments = tokens[index + 1:]
        if executable in {"bash", "sh", "zsh"}:
            for argument_index, argument in enumerate(arguments):
                if argument.startswith("-") and "c" in argument[1:]:
                    if argument_index + 1 < len(arguments):
                        results.extend(
                            command_position_executables(arguments[argument_index + 1])
                        )
                    break
        elif executable == "eval" and arguments:
            results.extend(command_position_executables(" ".join(arguments)))
        elif executable == "xargs":
            argument_index = 0
            options_with_values = {
                "-E",
                "-I",
                "-L",
                "-P",
                "-n",
                "-s",
                "--max-args",
                "--max-chars",
                "--max-lines",
                "--max-procs",
                "--replace",
            }
            while argument_index < len(arguments):
                argument = arguments[argument_index]
                if argument in options_with_values:
                    argument_index += 2
                elif argument.startswith("-"):
                    argument_index += 1
                else:
                    break
            if argument_index < len(arguments):
                results.extend(_segment_executables(arguments[argument_index:]))
        return tuple(results)
    return ()


def _strip_command_substitutions(text):
    sanitized = []
    substitutions = []
    index = 0
    quote = None
    escaped = False
    while index < len(text):
        character = text[index]
        if escaped:
            sanitized.append(character)
            escaped = False
            index += 1
            continue
        if character == "\\" and quote != "'":
            sanitized.append(character)
            escaped = True
            index += 1
            continue
        if character == "'" and quote != '"':
            quote = None if quote == "'" else "'"
            sanitized.append(character)
            index += 1
            continue
        if character == '"' and quote != "'":
            quote = None if quote == '"' else '"'
            sanitized.append(character)
            index += 1
            continue
        if (
            character == "$"
            and index + 1 < len(text)
            and text[index + 1] == "("
            and quote != "'"
        ):
            inner_start = index + 2
            cursor = inner_start
            depth = 1
            inner_quote = None
            inner_escaped = False
            while cursor < len(text):
                inner_character = text[cursor]
                if inner_escaped:
                    inner_escaped = False
                elif inner_character == "\\" and inner_quote != "'":
                    inner_escaped = True
                elif inner_character == "'" and inner_quote != '"':
                    inner_quote = None if inner_quote == "'" else "'"
                elif inner_character == '"' and inner_quote != "'":
                    inner_quote = None if inner_quote == '"' else '"'
                elif inner_quote is None and inner_character == "(":
                    depth += 1
                elif inner_quote is None and inner_character == ")":
                    depth -= 1
                    if depth == 0:
                        break
                cursor += 1
            if depth != 0:
                raise ValueError("unterminated command substitution")
            substitutions.append(text[inner_start:cursor])
            sanitized.append(" ")
            index = cursor + 1
            continue
        sanitized.append(character)
        index += 1
    return "".join(sanitized), substitutions


def command_position_executables(line):
    """Return every shell-segment executable using a quote-aware lexer."""
    stripped = line.strip()
    if stripped.startswith("run:"):
        stripped = stripped.removeprefix("run:").lstrip()
    try:
        stripped, substitutions = _strip_command_substitutions(stripped)
        lexer = shlex.shlex(
            stripped,
            posix=True,
            punctuation_chars="();&|",
        )
        lexer.commenters = "#"
        lexer.whitespace_split = True
        tokens = list(lexer)
    except ValueError:
        return ()

    segments = []
    current = []
    for token in tokens:
        if token and set(token) <= set("();&|"):
            if current:
                segments.append(current)
                current = []
            continue
        current.append(token)
    if current:
        segments.append(current)
    executables = []
    for segment in segments:
        executables.extend(_segment_executables(segment))
    for substitution in substitutions:
        executables.extend(command_position_executables(substitution))
    return tuple(executables)


def workflow_ambient_executables(line):
    """Conservatively find ambient tool tokens anywhere shell could dispatch them.

    These fixed workflows need no inert prose containing lowercase ambient tool names,
    so scanning every bare token is safer than pretending to fully interpret shell.
    The only legitimate bare tool words are pinned arguments to approved executables.
    Arithmetic expansion is data, not command dispatch, and is removed first.
    """
    policy_text = _ARITHMETIC_EXPANSION.sub(" ", line)
    policy_text = policy_text.replace("--language swift", "--language approved-language")
    policy_text = policy_text.replace(
        "--executable swiftformat",
        "--executable approved-formatter",
    )
    policy_text = policy_text.replace(
        "$GITHUB_WORKSPACE/.build/release-generator-venv/bin/python",
        "$GITHUB_WORKSPACE/.build/release-generator-venv/bin/approved-python",
    )
    violations = [
        match.group(1)
        for match in _FORBIDDEN_AMBIENT_TOKEN.finditer(policy_text)
    ]
    violations.extend(
        f"dynamic:{match.group(1)}"
        for match in _DYNAMIC_SHELL_DISPATCHER_TOKEN.finditer(policy_text)
    )
    for executable in command_position_executables(policy_text):
        if executable in _FORBIDDEN_AMBIENT_EXECUTABLES:
            violations.append(executable)
        elif executable.startswith("$") and executable not in _APPROVED_DYNAMIC_EXECUTABLES:
            violations.append(f"dynamic:{executable}")
    return tuple(dict.fromkeys(violations))


def workflow_run_lines(text):
    """Yield only shell source nested below YAML ``run:`` block scalars."""
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        if line.strip() not in {"run: |", "run: >"}:
            index += 1
            continue
        indentation = len(line) - len(line.lstrip())
        index += 1
        while index < len(lines):
            candidate = lines[index]
            candidate_indentation = len(candidate) - len(candidate.lstrip())
            if candidate.strip() and candidate_indentation <= indentation:
                break
            if candidate.strip():
                yield candidate.strip()
            index += 1


def has_one_isolated_setup_python_action(text):
    lines = text.splitlines()
    action_indices = [
        index
        for index, line in enumerate(lines)
        if re.match(r"^\s*- uses: actions/setup-python@", line)
    ]
    if len(action_indices) != 1:
        return False
    action_index = action_indices[0]
    action_line = lines[action_index]
    if action_line.strip() != "- uses: actions/setup-python@v5":
        return False
    indentation = len(action_line) - len(action_line.lstrip())
    block = []
    for line in lines[action_index + 1:]:
        if line.strip() and len(line) - len(line.lstrip()) <= indentation:
            break
        if line.strip():
            block.append((len(line) - len(line.lstrip()), line.strip()))
    return block == [
        (indentation + 2, "id: release-python"),
        (indentation + 2, "with:"),
        (indentation + 4, "python-version: '3.12'"),
        (indentation + 4, "update-environment: false"),
    ]

try:
    import generated_projection as projection
except ModuleNotFoundError:
    projection = None

import main as generator_main


class DuplicateItemsMapping(collections.abc.Mapping):
    """Hostile Mapping whose items collide after validation."""

    def __getitem__(self, key):
        if key == "Duplicate.swift":
            return "first"
        raise KeyError(key)

    def __iter__(self):
        return iter(("Duplicate.swift",))

    def __len__(self):
        return 1

    def items(self):
        return (
            ("Duplicate.swift", "first"),
            ("Duplicate.swift", "second"),
        )


class GeneratedProjectionTests(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.root = pathlib.Path(self.temporary_directory.name) / "output"

    def tearDown(self):
        self.temporary_directory.cleanup()

    async def _publish(self, expected_files, output_root=None):
        self.assertIsNotNone(
            projection,
            "generator.generated_projection closed-projection primitive is missing",
        )
        await projection.write_swift_projection(
            str(output_root or self.root),
            expected_files,
        )

    @staticmethod
    def _snapshot(root):
        if not root.exists():
            return None
        snapshot = []
        for path in sorted(root.rglob("*")):
            relative = path.relative_to(root).as_posix()
            if path.is_symlink():
                snapshot.append((relative, ("symlink", path.readlink().as_posix())))
            elif path.is_dir():
                snapshot.append((relative + "/", None))
            else:
                snapshot.append((relative, path.read_bytes()))
        return tuple(snapshot)

    async def test_marker_is_exact_and_expected_files_publish_in_sorted_order(self):
        self.assertIsNotNone(
            projection,
            "generator.generated_projection closed-projection primitive is missing",
        )
        self.assertEqual(projection.GENERATED_SWIFT_HEADER, EXPECTED_HEADER)

        expected = {
            "Zeta/Z.swift": EXPECTED_HEADER * 3 + "zeta\n",
            "Alpha.swift": "alpha\n",
            "Middle/M.swift": EXPECTED_HEADER + "middle\n",
        }
        with mock.patch.object(
            projection,
            "_write_bytes",
            wraps=projection._write_bytes,
        ) as write_spy:
            await self._publish(expected)

        written_paths = [
            (
                call.args[0].relative_to(self.root).as_posix()
                if call.args[0].is_absolute()
                else call.args[0].as_posix()
            )
            for call in write_spy.call_args_list
        ]
        self.assertEqual(
            written_paths,
            ["Alpha.swift", "Middle/M.swift", "Zeta/Z.swift"],
        )
        for relative, body in (
            ("Alpha.swift", "alpha\n"),
            ("Middle/M.swift", "middle\n"),
            ("Zeta/Z.swift", "zeta\n"),
        ):
            payload = (self.root / relative).read_text(encoding="utf-8")
            self.assertEqual(payload, EXPECTED_HEADER + body)
            self.assertEqual(payload.count(EXPECTED_HEADER), 1)

    async def test_only_unexpected_exactly_owned_swift_files_are_deleted(self):
        expected_path = self.root / "Expected.swift"
        owned_path = self.root / "Stale.swift"
        nested_owned_path = self.root / "Nested" / "Stale.swift"
        manual_path = self.root / "Manual.swift"
        nested_manual_path = self.root / "Nested" / "Manual.swift"
        near_miss_path = self.root / "NearMiss.swift"
        nested_near_miss_path = self.root / "Nested" / "NearMiss.swift"
        non_swift_path = self.root / "Owned.txt"
        nested_non_swift_path = self.root / "Nested" / "Owned.txt"
        empty_directory = self.root / "Empty" / "Preserved"
        empty_directory.mkdir(parents=True)
        nested_owned_path.parent.mkdir(parents=True, exist_ok=True)

        expected_path.write_bytes((EXPECTED_HEADER + "old\n").encode())
        owned_path.write_bytes((EXPECTED_HEADER + "stale\n").encode())
        nested_owned_path.write_bytes((EXPECTED_HEADER + "nested stale\n").encode())
        manual_path.write_bytes(b"manual\x00swift\n")
        nested_manual_path.write_bytes(b"nested manual\n")
        near_miss_path.write_bytes(b"// Generated by Petrel. DO NOT EDIT.\r\nmanual\n")
        nested_near_miss_path.write_bytes(b"// Generated by Petrel. DO NOT EDIT.manual\n")
        non_swift_path.write_bytes((EXPECTED_HEADER + "not swift\n").encode())
        nested_non_swift_path.write_bytes(b"nested non-swift\x00\n")

        survivors = {
            path: path.read_bytes()
            for path in (
                manual_path,
                nested_manual_path,
                near_miss_path,
                nested_near_miss_path,
                non_swift_path,
                nested_non_swift_path,
            )
        }

        await self._publish({"Expected.swift": "new\n"})

        self.assertEqual(expected_path.read_text(), EXPECTED_HEADER + "new\n")
        self.assertFalse(owned_path.exists())
        self.assertFalse(nested_owned_path.exists())
        for path, original_bytes in survivors.items():
            self.assertEqual(path.read_bytes(), original_bytes)
        self.assertTrue((self.root / "Nested").is_dir())
        self.assertTrue(empty_directory.is_dir())

    async def test_second_publication_is_byte_and_metadata_identical(self):
        expected = {
            "One.swift": "one\n",
            "Nested/Two.swift": EXPECTED_HEADER * 2 + "two\n",
        }
        await self._publish(expected)
        first_snapshot = self._snapshot(self.root)
        first_metadata = {
            path.relative_to(self.root).as_posix(): path.stat().st_mtime_ns
            for path in self.root.rglob("*.swift")
        }

        with mock.patch.object(
            projection,
            "_write_bytes",
            wraps=projection._write_bytes,
        ) as write_spy:
            await self._publish(dict(reversed(tuple(expected.items()))))

        self.assertEqual(self._snapshot(self.root), first_snapshot)
        self.assertEqual(
            {
                path.relative_to(self.root).as_posix(): path.stat().st_mtime_ns
                for path in self.root.rglob("*.swift")
            },
            first_metadata,
        )
        write_spy.assert_not_called()

    async def test_unchanged_fast_path_revalidates_content_after_preflight(self):
        expected_payload = EXPECTED_HEADER + "expected\n"
        self.root.mkdir(parents=True)
        target = self.root / "Expected.swift"
        target.write_text(expected_payload, encoding="utf-8")
        original_inode = target.stat().st_ino
        original_assert_root_identity = projection._assert_root_identity
        identity_checks = 0

        def rewrite_after_first_identity_check(*args, **kwargs):
            nonlocal identity_checks
            original_assert_root_identity(*args, **kwargs)
            identity_checks += 1
            if identity_checks == 1:
                target.write_text(EXPECTED_HEADER + "changed in place\n", encoding="utf-8")
                self.assertEqual(target.stat().st_ino, original_inode)

        with mock.patch.object(
            projection,
            "_assert_root_identity",
            side_effect=rewrite_after_first_identity_check,
        ):
            await self._publish({"Expected.swift": "expected\n"})

        self.assertEqual(target.read_text(encoding="utf-8"), expected_payload)

    async def test_expected_mutation_after_final_read_is_detected_before_skip(self):
        expected_payload = EXPECTED_HEADER + "expected\n"
        changed_payload = EXPECTED_HEADER + "changed after read\n"
        self.root.mkdir(parents=True)
        target = self.root / "Expected.swift"
        target.write_text(expected_payload, encoding="utf-8")
        original_read = projection._read_regular_file_at
        expected_reads = 0
        mutated = False

        def mutate_immediately_after_final_read(parent_fd, name, expected, context):
            nonlocal expected_reads, mutated
            content = original_read(parent_fd, name, expected, context)
            if context == "expected target Expected.swift":
                expected_reads += 1
                if expected_reads == 2:
                    file_fd = os.open(
                        name,
                        os.O_WRONLY | os.O_TRUNC,
                        dir_fd=parent_fd,
                    )
                    try:
                        os.write(file_fd, changed_payload.encode("utf-8"))
                    finally:
                        os.close(file_fd)
                    mutated = True
            return content

        with mock.patch.object(
            projection,
            "_read_regular_file_at",
            side_effect=mutate_immediately_after_final_read,
        ):
            with self.assertRaisesRegex(ValueError, "content|snapshot|changed|identity"):
                await self._publish({"Expected.swift": "expected\n"})

        self.assertTrue(mutated)
        self.assertEqual(target.read_text(encoding="utf-8"), changed_payload)

    async def test_stale_mutation_after_final_read_is_restored_and_rejected(self):
        changed_payload = b"manual replacement after read\n"
        self.root.mkdir(parents=True)
        stale = self.root / "Stale.swift"
        stale.write_text(EXPECTED_HEADER + "stale\n", encoding="utf-8")
        original_read = projection._read_regular_file_at
        mutated = False

        def mutate_immediately_after_final_read(parent_fd, name, expected, context):
            nonlocal mutated
            content = original_read(parent_fd, name, expected, context)
            if context == "owned stale Swift file Stale.swift" and not mutated:
                file_fd = os.open(
                    name,
                    os.O_WRONLY | os.O_TRUNC,
                    dir_fd=parent_fd,
                )
                try:
                    os.write(file_fd, changed_payload)
                finally:
                    os.close(file_fd)
                mutated = True
            return content

        with mock.patch.object(
            projection,
            "_read_regular_file_at",
            side_effect=mutate_immediately_after_final_read,
        ):
            with self.assertRaisesRegex(ValueError, "content|snapshot|changed|identity"):
                await self._publish({})

        self.assertTrue(mutated)
        self.assertEqual(stale.read_bytes(), changed_payload)

    async def test_temp_source_name_substitution_is_rejected_without_installing_symlink(self):
        outside = pathlib.Path(self.temporary_directory.name) / "manual.swift"
        outside.write_bytes(b"manual\n")
        original_revalidate = projection._revalidate_destination
        substituted = False

        def substitute_temp_after_destination_check(
            parent_fd, leaf, relative_path, existing
        ):
            nonlocal substituted
            original_revalidate(parent_fd, leaf, relative_path, existing)
            candidates = [
                name
                for name in os.listdir(parent_fd)
                if name.startswith(".petrel-projection-") and name.endswith(".tmp")
            ]
            self.assertEqual(len(candidates), 1)
            temporary_name = candidates[0]
            os.unlink(temporary_name, dir_fd=parent_fd)
            os.symlink(str(outside), temporary_name, dir_fd=parent_fd)
            substituted = True

        with mock.patch.object(
            projection,
            "_revalidate_destination",
            side_effect=substitute_temp_after_destination_check,
        ):
            with self.assertRaises(ValueError):
                await self._publish({"Expected.swift": "body\n"})

        target = self.root / "Expected.swift"
        self.assertTrue(substituted)
        self.assertFalse(os.path.lexists(target))
        self.assertFalse(target.is_symlink())
        self.assertEqual(outside.read_bytes(), b"manual\n")

    async def test_cleanup_failure_still_closes_temporary_and_parent_descriptors(self):
        original_open = projection.os.open
        captured = {}

        def capture_projection_descriptors(path, flags, *args, **kwargs):
            descriptor = original_open(path, flags, *args, **kwargs)
            if (
                isinstance(path, str)
                and path.startswith(".petrel-projection-")
                and path.endswith(".tmp")
            ):
                captured["temporary"] = descriptor
            return descriptor

        def fail_cleanup(parent_fd, temporary_name, retained_node):
            captured["parent"] = parent_fd
            raise RuntimeError("forced temporary cleanup failure")

        with (
            mock.patch.object(
                projection.os,
                "open",
                side_effect=capture_projection_descriptors,
            ),
            mock.patch.object(
                projection,
                "_cleanup_temporary_name",
                side_effect=fail_cleanup,
            ),
        ):
            with self.assertRaisesRegex(
                RuntimeError,
                "forced temporary cleanup failure",
            ):
                await self._publish({"Expected.swift": "body\n"})

        self.assertEqual(set(captured), {"parent", "temporary"})
        leaked = []
        for name, descriptor in captured.items():
            try:
                os.fstat(descriptor)
            except OSError as error:
                self.assertEqual(error.errno, getattr(os, "EBADF", 9))
            else:
                leaked.append(name)
                os.close(descriptor)
        self.assertEqual(leaked, [])

    async def test_quarantine_setup_failure_closes_descriptor_and_removes_directory(self):
        self.root.mkdir(parents=True)
        stale = self.root / "Stale.swift"
        stale.write_text(EXPECTED_HEADER + "stale\n", encoding="utf-8")
        original_open = projection.os.open
        captured_descriptors = []

        def capture_quarantine_descriptor(path, flags, *args, **kwargs):
            descriptor = original_open(path, flags, *args, **kwargs)
            if (
                isinstance(path, str)
                and path.startswith(".petrel-projection-quarantine-")
            ):
                captured_descriptors.append(descriptor)
            return descriptor

        with (
            mock.patch.object(
                projection.os,
                "open",
                side_effect=capture_quarantine_descriptor,
            ),
            mock.patch.object(
                projection.os,
                "fchmod",
                side_effect=RuntimeError("forced quarantine fchmod failure"),
            ),
        ):
            with self.assertRaisesRegex(
                RuntimeError,
                "forced quarantine fchmod failure",
            ):
                await self._publish({})

        self.assertEqual(len(captured_descriptors), 1)
        leaked = []
        for descriptor in captured_descriptors:
            try:
                os.fstat(descriptor)
            except OSError as error:
                self.assertEqual(error.errno, getattr(os, "EBADF", 9))
            else:
                leaked.append(descriptor)
                os.close(descriptor)
        leftovers = list(self.root.glob(".petrel-projection-quarantine-*"))
        for path in leftovers:
            path.rmdir()
        self.assertEqual(leaked, [])
        self.assertEqual(leftovers, [])

    async def test_directory_open_helpers_close_descriptors_when_fstat_fails(self):
        self.root.mkdir(parents=True)
        child = self.root / "Child"
        child.mkdir()
        original_open = projection.os.open
        captured = []

        def capture_open(path, flags, *args, **kwargs):
            descriptor = original_open(path, flags, *args, **kwargs)
            captured.append(descriptor)
            return descriptor

        with (
            mock.patch.object(projection.os, "open", side_effect=capture_open),
            mock.patch.object(
                projection.os,
                "fstat",
                side_effect=OSError(errno.EIO, "forced root fstat failure"),
            ),
        ):
            with self.assertRaisesRegex(OSError, "forced root fstat failure"):
                projection._open_root(self.root)

        parent_fd = original_open(self.root, projection._DIRECTORY_FLAGS)
        try:
            expected = projection._node_from_stat(os.lstat(child))
            with (
                mock.patch.object(projection.os, "open", side_effect=capture_open),
                mock.patch.object(
                    projection.os,
                    "fstat",
                    side_effect=OSError(errno.EIO, "forced child fstat failure"),
                ),
            ):
                with self.assertRaisesRegex(OSError, "forced child fstat failure"):
                    projection._open_directory_at(parent_fd, "Child", expected)
        finally:
            os.close(parent_fd)

        self.assertEqual(len(captured), 2)
        leaked = []
        for descriptor in captured:
            try:
                os.fstat(descriptor)
            except OSError as error:
                self.assertEqual(error.errno, errno.EBADF)
            else:
                leaked.append(descriptor)
                os.close(descriptor)
        self.assertEqual(leaked, [])

    async def test_relocated_descendant_before_transaction_is_rejected_without_redirect(self):
        (self.root / "Dir").mkdir(parents=True)
        outside = pathlib.Path(self.temporary_directory.name) / "outside"
        outside.mkdir()
        original_write = projection._write_bytes
        relocated = False

        def relocate_parent_then_write(
            relative_path, root_fd, directories, payload, existing
        ):
            nonlocal relocated
            if not relocated:
                relocated = True
                (self.root / "Dir").rename(outside / "Dir")
                (self.root / "Dir").mkdir()
            return original_write(
                relative_path, root_fd, directories, payload, existing
            )

        with mock.patch.object(
            projection,
            "_write_bytes",
            side_effect=relocate_parent_then_write,
        ):
            with self.assertRaises(ValueError):
                await self._publish({"Dir/Expected.swift": "body\n"})

        self.assertTrue(relocated)
        self.assertFalse((outside / "Dir" / "Expected.swift").exists())
        self.assertFalse((self.root / "Dir" / "Expected.swift").exists())

    async def test_manual_stale_replacement_after_quarantine_survives(self):
        self.root.mkdir(parents=True)
        stale = self.root / "Stale.swift"
        manual_bytes = b"manual replacement after quarantine\n"
        stale.write_text(EXPECTED_HEADER + "stale\n", encoding="utf-8")
        original_rename = projection.os.rename
        replaced = False

        def replace_leaf_after_quarantine(source, destination, *args, **kwargs):
            nonlocal replaced
            result = original_rename(source, destination, *args, **kwargs)
            if source == "Stale.swift" and str(destination).startswith("stale-"):
                parent_fd = kwargs["src_dir_fd"]
                replacement_fd = os.open(
                    source,
                    os.O_WRONLY | os.O_CREAT | os.O_EXCL,
                    0o600,
                    dir_fd=parent_fd,
                )
                try:
                    os.write(replacement_fd, manual_bytes)
                finally:
                    os.close(replacement_fd)
                replaced = True
            return result

        with mock.patch.object(
            projection.os,
            "rename",
            side_effect=replace_leaf_after_quarantine,
        ):
            await self._publish({})

        self.assertTrue(replaced)
        self.assertEqual(stale.read_bytes(), manual_bytes)
        self.assertEqual(
            list(self.root.glob(".petrel-projection-quarantine-*")),
            [],
        )

    async def test_cleanup_never_directly_unlinks_a_live_stale_leaf(self):
        self.root.mkdir(parents=True)
        stale = self.root / "Stale.swift"
        moved = pathlib.Path(self.temporary_directory.name) / "moved-stale.swift"
        stale.write_text(EXPECTED_HEADER + "stale\n", encoding="utf-8")
        original_unlink = projection.os.unlink
        substituted = False

        def substitute_manual_at_checked_leaf(path, *args, **kwargs):
            nonlocal substituted
            if path == "Stale.swift" and not substituted:
                substituted = True
                stale.rename(moved)
                stale.write_bytes(b"manual replacement\n")
            return original_unlink(path, *args, **kwargs)

        with mock.patch.object(
            projection.os,
            "unlink",
            side_effect=substitute_manual_at_checked_leaf,
        ):
            await self._publish({"Expected.swift": "body\n"})

        self.assertFalse(substituted)
        self.assertFalse(moved.exists())
        self.assertFalse(stale.exists())
        self.assertEqual(
            (self.root / "Expected.swift").read_text(encoding="utf-8"),
            EXPECTED_HEADER + "body\n",
        )

    async def test_non_swift_expected_target_rejects_before_root_creation(self):
        self.assertFalse(self.root.exists())
        with self.assertRaisesRegex(ValueError, "lowercase|Swift|\\.swift|target"):
            await self._publish({"Generated.txt": "not Swift\n"})
        self.assertFalse(self.root.exists())

    def test_writer_documents_exclusive_generation_ownership_assumption(self):
        documentation = projection.write_swift_projection.__doc__ or ""
        self.assertIn("exclusive generation ownership", documentation)
        self.assertIn("uncooperative concurrent writer", documentation)

    async def test_invalid_paths_and_normalized_collisions_reject_before_mutation(self):
        invalid_mappings = (
            {"": "empty"},
            {".": "dot"},
            {"./": "dot slash"},
            {"/Absolute.swift": "absolute"},
            {"..": "parent"},
            {"../Escape.swift": "escape"},
            {"Nested/../../Escape.swift": "escape"},
            {"Nested/./Alias.swift": "alias"},
            {"Nested//Alias.swift": "alias"},
            {"Nested/../Alias.swift": "alias"},
            {"Nested/Alias.swift/": "alias"},
            {"C:\\Absolute.swift": "windows absolute"},
            DuplicateItemsMapping(),
        )

        for index, invalid in enumerate(invalid_mappings):
            with self.subTest(invalid=invalid):
                case_root = self.root / str(index)
                case_root.mkdir(parents=True)
                sentinel = case_root / "Sentinel.swift"
                stale = case_root / "Stale.swift"
                sentinel.write_bytes(b"manual sentinel\x00\n")
                stale.write_text(EXPECTED_HEADER + "stale\n", encoding="utf-8")
                before = self._snapshot(case_root)

                with self.assertRaisesRegex(ValueError, "path|target|relative|collision"):
                    await self._publish(invalid, output_root=case_root)

                self.assertEqual(self._snapshot(case_root), before)

    async def test_invalid_paths_do_not_create_an_absent_output_root(self):
        self.assertFalse(self.root.exists())
        with self.assertRaisesRegex(ValueError, "path|relative"):
            await self._publish({"../Escape.swift": "escape"})
        self.assertFalse(self.root.exists())

    async def test_existing_symlink_cannot_escape_the_output_root(self):
        self.root.mkdir(parents=True)
        outside = pathlib.Path(self.temporary_directory.name) / "outside"
        outside.mkdir()
        link = self.root / "Linked"
        link.symlink_to(outside, target_is_directory=True)
        sentinel = self.root / "Manual.swift"
        sentinel.write_bytes(b"manual\n")
        before = self._snapshot(self.root)

        with self.assertRaisesRegex(ValueError, "escape|root|path|symlink"):
            await self._publish({"Linked/Escape.swift": "escape\n"})

        self.assertEqual(self._snapshot(self.root), before)
        self.assertFalse((outside / "Escape.swift").exists())

    async def test_expected_leaf_symlink_to_manual_file_is_rejected_before_mutation(self):
        self.root.mkdir(parents=True)
        manual = self.root / "Manual.swift"
        expected = self.root / "Expected.swift"
        manual.write_bytes(b"manual swift\x00\n")
        expected.symlink_to(manual.name)
        before = self._snapshot(self.root)

        with self.assertRaisesRegex(ValueError, "symlink|target|path"):
            await self._publish({"Expected.swift": "generated\n"})

        self.assertEqual(self._snapshot(self.root), before)
        self.assertEqual(manual.read_bytes(), b"manual swift\x00\n")
        self.assertEqual(expected.readlink(), pathlib.Path("Manual.swift"))

    async def test_expected_internal_symlink_is_rejected_even_when_it_stays_inside_root(self):
        self.root.mkdir(parents=True)
        real_directory = self.root / "Real"
        real_directory.mkdir()
        manual = real_directory / "Manual.swift"
        manual.write_bytes(b"manual\n")
        (self.root / "Linked").symlink_to(real_directory.name, target_is_directory=True)
        before = self._snapshot(self.root)

        with self.assertRaisesRegex(ValueError, "symlink|ancestor|path"):
            await self._publish({"Linked/Generated.swift": "generated\n"})

        self.assertEqual(self._snapshot(self.root), before)
        self.assertFalse((real_directory / "Generated.swift").exists())

    async def test_output_root_symlink_is_rejected_before_mutation(self):
        actual_root = pathlib.Path(self.temporary_directory.name) / "actual-output"
        actual_root.mkdir()
        manual = actual_root / "Manual.swift"
        manual.write_bytes(b"manual\n")
        self.root.symlink_to(actual_root, target_is_directory=True)
        before = self._snapshot(actual_root)

        with self.assertRaisesRegex(ValueError, "root|symlink"):
            await self._publish({"Expected.swift": "generated\n"})

        self.assertEqual(self._snapshot(actual_root), before)
        self.assertFalse((actual_root / "Expected.swift").exists())

    async def test_root_path_swap_during_async_write_cannot_redirect_write_or_cleanup(self):
        self.root.mkdir(parents=True)
        moved_root = pathlib.Path(self.temporary_directory.name) / "opened-output"
        replacement_owned_bytes = (EXPECTED_HEADER + "replacement\n").encode()
        original_write = projection._write_bytes
        swapped = False

        def swap_root_then_write(*args, **kwargs):
            nonlocal swapped
            if not swapped:
                swapped = True
                self.root.rename(moved_root)
                self.root.mkdir()
                (self.root / "Outside.swift").write_bytes(replacement_owned_bytes)
                (self.root / "Manual.swift").write_bytes(b"outside manual\n")
            return original_write(*args, **kwargs)

        with mock.patch.object(projection, "_write_bytes", swap_root_then_write):
            with self.assertRaisesRegex(ValueError, "root|identity|changed"):
                await self._publish({"Expected.swift": "generated\n"})

        self.assertTrue(swapped)
        self.assertEqual(
            (moved_root / "Expected.swift").read_text(encoding="utf-8"),
            EXPECTED_HEADER + "generated\n",
        )
        self.assertEqual(
            (self.root / "Outside.swift").read_bytes(),
            replacement_owned_bytes,
        )
        self.assertEqual(
            (self.root / "Manual.swift").read_bytes(),
            b"outside manual\n",
        )
        self.assertFalse((self.root / "Expected.swift").exists())

    async def test_expected_case_and_unicode_aliases_reject_before_root_creation(self):
        decomposed = unicodedata.normalize("NFD", "Café.swift")
        cases = (
            {"Case.swift": "one", "case.swift": "two"},
            {"Dir/One.swift": "one", "dir/Two.swift": "two"},
            {"Café.swift": "one", decomposed: "two"},
        )
        for index, expected in enumerate(cases):
            with self.subTest(expected=expected):
                case_root = pathlib.Path(self.temporary_directory.name) / f"expected-alias-{index}"
                self.assertFalse(case_root.exists())
                with self.assertRaisesRegex(ValueError, "alias|collision|spelling"):
                    await self._publish(expected, output_root=case_root)
                self.assertFalse(case_root.exists())

    async def test_expected_path_aliasing_existing_spelling_rejects_without_mutation(self):
        cases = (
            ("case.swift", "Case.swift"),
            (unicodedata.normalize("NFD", "Café.swift"), "Café.swift"),
        )
        for index, (existing_name, expected_name) in enumerate(cases):
            with self.subTest(existing_name=existing_name, expected_name=expected_name):
                case_root = pathlib.Path(self.temporary_directory.name) / f"alias-{index}"
                case_root.mkdir()
                existing = case_root / existing_name
                existing.write_bytes(b"manual alias\x00\n")
                before = self._snapshot(case_root)

                with self.assertRaisesRegex(ValueError, "alias|spelling|collision"):
                    await self._publish(
                        {expected_name: "generated\n"},
                        output_root=case_root,
                    )

                self.assertEqual(self._snapshot(case_root), before)
                self.assertEqual(existing.read_bytes(), b"manual alias\x00\n")

    async def test_expected_hardlink_is_rejected_before_mutating_shared_inode(self):
        self.root.mkdir(parents=True)
        manual = self.root / "Manual.swift"
        expected = self.root / "Expected.swift"
        manual.write_bytes(b"manual hardlink\x00\n")
        os.link(manual, expected)
        before = self._snapshot(self.root)

        with self.assertRaisesRegex(ValueError, "hardlink|link count|inode"):
            await self._publish({"Expected.swift": "generated\n"})

        self.assertEqual(self._snapshot(self.root), before)
        self.assertEqual(manual.read_bytes(), b"manual hardlink\x00\n")
        self.assertEqual(expected.read_bytes(), b"manual hardlink\x00\n")

    async def test_owned_stale_hardlink_rejects_before_any_expected_write(self):
        self.root.mkdir(parents=True)
        stale = self.root / "Stale.swift"
        shared = self.root / "Shared.swift"
        stale.write_text(EXPECTED_HEADER + "stale\n", encoding="utf-8")
        os.link(stale, shared)
        before = self._snapshot(self.root)

        with self.assertRaisesRegex(ValueError, "hardlink|link count|inode"):
            await self._publish({"Expected.swift": "generated\n"})

        self.assertEqual(self._snapshot(self.root), before)
        self.assertFalse((self.root / "Expected.swift").exists())

    async def test_manual_hardlinks_and_unexpected_symlink_directories_survive(self):
        self.root.mkdir(parents=True)
        manual = self.root / "Manual.swift"
        manual_alias = self.root / "ManualAlias.swift"
        manual.write_bytes(b"manual hardlink\x00\n")
        os.link(manual, manual_alias)

        outside = pathlib.Path(self.temporary_directory.name) / "outside"
        outside.mkdir()
        outside_owned = outside / "Outside.swift"
        outside_owned.write_text(EXPECTED_HEADER + "outside\n", encoding="utf-8")
        linked = self.root / "Linked"
        linked.symlink_to(outside, target_is_directory=True)

        await self._publish({"Expected.swift": "generated\n"})

        self.assertEqual(manual.read_bytes(), b"manual hardlink\x00\n")
        self.assertEqual(manual_alias.read_bytes(), b"manual hardlink\x00\n")
        self.assertTrue(linked.is_symlink())
        self.assertEqual(linked.readlink(), outside)
        self.assertEqual(
            outside_owned.read_text(encoding="utf-8"),
            EXPECTED_HEADER + "outside\n",
        )

    async def test_atomic_replacement_preserves_existing_mode(self):
        self.root.mkdir(parents=True)
        target = self.root / "Expected.swift"
        target.write_text(EXPECTED_HEADER + "old\n", encoding="utf-8")
        target.chmod(0o640)

        await self._publish({"Expected.swift": "new\n"})

        self.assertEqual(target.read_text(encoding="utf-8"), EXPECTED_HEADER + "new\n")
        self.assertEqual(stat.S_IMODE(target.stat().st_mode), 0o640)

    async def test_later_sorted_filesystem_conflicts_reject_before_any_write(self):
        cases = ("leaf-directory", "parent-file")
        for index, conflict in enumerate(cases):
            with self.subTest(conflict=conflict):
                case_root = pathlib.Path(self.temporary_directory.name) / f"conflict-{index}"
                case_root.mkdir()
                expected = {"A.swift": "would otherwise write first\n"}
                if conflict == "leaf-directory":
                    (case_root / "Z.swift").mkdir()
                    expected["Z.swift"] = "conflict\n"
                else:
                    (case_root / "ZParent").write_bytes(b"manual parent\n")
                    expected["ZParent/Child.swift"] = "conflict\n"
                before = self._snapshot(case_root)

                try:
                    await self._publish(expected, output_root=case_root)
                except ValueError as error:
                    self.assertRegex(str(error), "directory|ancestor|regular|node")
                except Exception as error:
                    self.fail(
                        f"expected focused ValueError, got {type(error).__name__}: {error}"
                    )
                else:
                    self.fail("filesystem conflict was not rejected")

                self.assertEqual(self._snapshot(case_root), before)
                self.assertFalse((case_root / "A.swift").exists())

    async def test_mapping_prefix_conflict_rejects_before_absent_root_creation(self):
        self.assertFalse(self.root.exists())
        try:
            await self._publish(
                {
                    "B.swift": "leaf\n",
                    "B.swift/C.swift": "descendant\n",
                }
            )
        except ValueError as error:
            self.assertRegex(str(error), "ancestor|prefix|structure|collision")
        except Exception as error:
            self.fail(f"expected focused ValueError, got {type(error).__name__}: {error}")
        else:
            self.fail("mapping prefix conflict was not rejected")
        self.assertFalse(self.root.exists())


class GeneratorProjectionPublicationTests(unittest.TestCase):
    def setUp(self):
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.root = pathlib.Path(self.temporary_directory.name)
        self.core_lexicons = self.root / "core-lexicons"
        self.overlay_lexicons = self.root / "overlay-lexicons"
        self.reference_lexicons = self.root / "reference-lexicons"
        self.core_lexicons.mkdir()
        self.overlay_lexicons.mkdir()
        self.reference_lexicons.mkdir()

        self._write_object_lexicon(
            self.core_lexicons,
            "com.example.core.defs",
        )
        self._write_query_lexicon(
            self.core_lexicons,
            "com.example.core.getItem",
        )
        self._write_object_lexicon(
            self.overlay_lexicons,
            "blue.catbird.test.item",
        )
        self._write_query_lexicon(
            self.overlay_lexicons,
            "blue.catbird.test.getItem",
        )
        self._write_object_lexicon(
            self.reference_lexicons,
            "blue.example.core.item",
        )

    def tearDown(self):
        self.temporary_directory.cleanup()

    @staticmethod
    def _write_object_lexicon(directory, lexicon_id):
        lexicon = {
            "lexicon": 1,
            "id": lexicon_id,
            "defs": {
                "main": {
                    "type": "object",
                    "required": ["value"],
                    "properties": {"value": {"type": "string"}},
                }
            },
        }
        (directory / f"{lexicon_id}.json").write_text(
            json.dumps(lexicon),
            encoding="utf-8",
        )

    @staticmethod
    def _write_query_lexicon(directory, lexicon_id):
        lexicon = {
            "lexicon": 1,
            "id": lexicon_id,
            "defs": {
                "main": {
                    "type": "query",
                    "output": {
                        "encoding": "application/json",
                        "schema": {
                            "type": "object",
                            "required": ["ok"],
                            "properties": {"ok": {"type": "boolean"}},
                        },
                    },
                }
            },
        }
        (directory / f"{lexicon_id}.json").write_text(
            json.dumps(lexicon),
            encoding="utf-8",
        )

    def _write_manifest(
        self,
        name,
        *,
        kind,
        package_name,
        emit,
        output,
        reference=(),
    ):
        manifest = {
            "package": {
                "kind": kind,
                "name": package_name,
                "core_namespace_roots": ["blue"],
            },
            "lexicons": {
                "emit": [str(path) for path in emit],
                "reference": [str(path) for path in reference],
                "exclude_namespaces": [],
            },
            "swift": {"output": str(output)},
        }
        path = self.root / f"{name}.json"
        path.write_text(json.dumps(manifest), encoding="utf-8")
        return path

    @staticmethod
    def _run_manifest(manifest):
        asyncio.run(generator_main.run_manifest(str(manifest), language="swift"))

    def test_core_manifest_publishes_one_complete_projection(self):
        output = self.root / "core-output"
        manifest = self._write_manifest(
            "core",
            kind="core",
            package_name="Petrel",
            emit=(self.core_lexicons,),
            output=output,
        )
        writer = mock.AsyncMock()
        with mock.patch.object(generator_main, "write_swift_projection", writer, create=True):
            self._run_manifest(manifest)

        writer.assert_awaited_once()
        published_root, expected_files = writer.await_args.args
        self.assertEqual(pathlib.Path(published_root), output)
        self.assertEqual(
            set(expected_files),
            {
                "Client/ATProtoClient+Generated.swift",
                "Core/Types/ATProtocolValueContainer.swift",
                "Lexicons/Com/Example/ComExampleCoreDefs.swift",
                "Lexicons/Com/Example/ComExampleCoreGetItem.swift",
            },
        )
        self.assertIn("struct ComExampleCoreDefs", expected_files[
            "Lexicons/Com/Example/ComExampleCoreDefs.swift"
        ])
        self.assertIn("func getItem", expected_files[
            "Lexicons/Com/Example/ComExampleCoreGetItem.swift"
        ])
        value_container = expected_files["Core/Types/ATProtocolValueContainer.swift"]
        self.assertIn(
            "self = try ATProtocolValueContainer.decodeValue(from: decoder)",
            value_container,
        )
        self.assertIn("container.decode(UInt64.self)", value_container)
        self.assertNotIn("container.decode(Double.self)", value_container)
        self.assertNotIn("try? decoder.container", value_container)
        self.assertIn("case \"$link\":", value_container)
        self.assertIn("case \"$bytes\":", value_container)
        self.assertIn(
            "typedValue.encodedDAGCBOR() == rawObject.encodedDAGCBOR()",
            value_container,
        )
        self.assertIn("try container.decodeNil(forKey: key)", value_container)
        self.assertIn("try unkeyedContainer.decodeNil()", value_container)
        self.assertLess(
            value_container.index("decodeSpecialObject("),
            value_container.index('stringValue == "$type"'),
        )
        self.assertFalse(output.exists())

    def test_overlay_manifest_publishes_one_complete_projection(self):
        output = self.root / "overlay-output"
        manifest = self._write_manifest(
            "overlay",
            kind="overlay",
            package_name="PetrelCatbird",
            emit=(self.overlay_lexicons,),
            output=output,
            reference=(self.reference_lexicons,),
        )
        writer = mock.AsyncMock()
        with mock.patch.object(generator_main, "write_swift_projection", writer, create=True):
            self._run_manifest(manifest)

        writer.assert_awaited_once()
        published_root, expected_files = writer.await_args.args
        self.assertEqual(pathlib.Path(published_root), output)
        self.assertEqual(
            set(expected_files),
            {
                "Client/ATProtoClient+PetrelCatbird.swift",
                "Client/PetrelCatbirdLexicons.swift",
                "Lexicons/Blue/Catbird/BlueCatbirdTestGetItem.swift",
                "Lexicons/Blue/Catbird/BlueCatbirdTestItem.swift",
            },
        )
        self.assertNotIn("Core/Types/ATProtocolValueContainer.swift", expected_files)
        self.assertNotIn("Client/ATProtoClient+Generated.swift", expected_files)
        for payload in expected_files.values():
            self.assertIn("import Petrel", payload)
        self.assertIn(
            "func getItem",
            expected_files["Lexicons/Blue/Catbird/BlueCatbirdTestGetItem.swift"],
        )
        self.assertFalse(output.exists())

    def test_real_generator_removes_stale_owned_and_preserves_manual_files(self):
        output = self.root / "real-output"
        output.mkdir()
        stale = output / "Nested" / "Stale.swift"
        manual = output / "Nested" / "Manual.swift"
        non_swift = output / "Nested" / "Notes.txt"
        stale.parent.mkdir()
        stale.write_text(EXPECTED_HEADER + "stale\n", encoding="utf-8")
        manual.write_bytes(b"manual swift\x00\n")
        non_swift.write_bytes(b"manual text\x00\n")
        manual_bytes = manual.read_bytes()
        non_swift_bytes = non_swift.read_bytes()
        manifest = self._write_manifest(
            "real",
            kind="core",
            package_name="Petrel",
            emit=(self.core_lexicons,),
            output=output,
        )

        self._run_manifest(manifest)

        self.assertFalse(stale.exists())
        self.assertEqual(manual.read_bytes(), manual_bytes)
        self.assertEqual(non_swift.read_bytes(), non_swift_bytes)
        generated = sorted(output.rglob("*.swift"))
        self.assertGreaterEqual(len(generated), 4)
        for path in generated:
            if path == manual:
                continue
            self.assertTrue(path.read_bytes().startswith(EXPECTED_HEADER.encode()))
        first = {
            path.relative_to(output).as_posix(): (path.read_bytes(), path.stat().st_mtime_ns)
            for path in output.rglob("*")
            if path.is_file()
        }

        self._run_manifest(manifest)

        second = {
            path.relative_to(output).as_posix(): (path.read_bytes(), path.stat().st_mtime_ns)
            for path in output.rglob("*")
            if path.is_file()
        }
        self.assertEqual(second, first)

    def test_legacy_swift_entrypoint_publishes_once(self):
        output = self.root / "legacy-output"
        writer = mock.AsyncMock()
        with mock.patch.object(generator_main, "write_swift_projection", writer, create=True):
            asyncio.run(
                generator_main.main(
                    str(self.core_lexicons),
                    str(output),
                    language="swift",
                )
            )

        writer.assert_awaited_once()
        self.assertFalse(output.exists())

    def test_legacy_both_entrypoint_publishes_swift_once(self):
        output = self.root / "legacy-both-output"
        writer = mock.AsyncMock()
        kotlin_writer = mock.AsyncMock()
        with (
            mock.patch.object(generator_main, "write_swift_projection", writer),
            mock.patch.object(
                generator_main,
                "generate_kotlin_from_lexicons_recursive",
                kotlin_writer,
            ),
        ):
            asyncio.run(
                generator_main.main(
                    str(self.core_lexicons),
                    str(output),
                    language="both",
                )
            )

        writer.assert_awaited_once()
        kotlin_writer.assert_awaited_once()
        self.assertFalse(output.exists())


class RegenerationScriptContractTests(unittest.TestCase):
    def setUp(self):
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.root = pathlib.Path(self.temporary_directory.name) / "fixture"
        self.bin = self.root / "fake-bin"
        self.calls = self.root / "tool-calls.log"
        self.ambient_calls = self.root / "ambient-tool-calls.log"
        self.vcs_calls = self.root / "vcs-calls.log"
        (self.root / "Scripts").mkdir(parents=True)
        (self.root / "generator" / "manifests").mkdir(parents=True)
        (self.root / "Sources" / "Petrel" / "Generated").mkdir(parents=True)
        self.bin.mkdir()
        (self.root / "run.py").write_text("# fixture\n", encoding="utf-8")

        script = REPOSITORY_ROOT / "Scripts" / "regenerate-generated.sh"
        self.assertTrue(script.is_file(), "regeneration script is missing")
        self.script_text = script.read_text(encoding="utf-8")
        self.script = self.root / "Scripts" / "regenerate-generated.sh"
        shutil.copy2(script, self.script)
        self.script.chmod(0o755)

        tool_body = """#!/usr/bin/env bash
set -euo pipefail
{
  printf '%s' "$(basename "$0")"
  printf '|%s' "$@"
  printf '\n'
} >> "$CALL_LOG"
"""
        for name in ("release-python", "release-mint"):
            self._write_executable(name, tool_body)
        ambient_tool_body = """#!/usr/bin/env bash
set -euo pipefail
{
  printf '%s' "$(basename "$0")"
  printf '|%s' "$@"
  printf '\n'
} >> "$AMBIENT_CALL_LOG"
exit 97
"""
        for name in sorted(_FORBIDDEN_AMBIENT_EXECUTABLES):
            self._write_executable(name, ambient_tool_body)

        vcs_body = r"""#!/usr/bin/env bash
set -euo pipefail
{
  printf '%s' "$(basename "$0")"
  printf '|%s' "$@"
  printf '\n'
} >> "$VCS_CALL_LOG"
name=$(basename "$0")
upper=$(printf '%s' "$name" | /usr/bin/tr '[:lower:]' '[:upper:]')
eval "failure=\${FAKE_${upper}_FAIL:-0}"
eval "dirty=\${FAKE_${upper}_DIRTY:-0}"
if [[ $failure == 1 ]]; then
  exit 23
fi
if [[ $dirty == 1 ]]; then
  printf 'M dirty-generated-output\n'
fi
"""
        self._write_executable("jj", vcs_body)
        self._write_executable("git", vcs_body)

        self.environment = os.environ.copy()
        self.environment.update(
            {
                "PATH": f"{self.bin}:/usr/bin:/bin",
                "CALL_LOG": str(self.calls),
                "AMBIENT_CALL_LOG": str(self.ambient_calls),
                "VCS_CALL_LOG": str(self.vcs_calls),
                "PETREL_PYTHON": str(self.bin / "release-python"),
                "RELEASE_MINT": str(self.bin / "release-mint"),
                "RELEASE_SWIFT": str(self.bin / "swift"),
                "RELEASE_XCODEBUILD": str(self.bin / "xcodebuild"),
                "RELEASE_XCRUN": str(self.bin / "xcrun"),
                "DEVELOPER_DIR": str(self.root / "selected-toolchain"),
                "MINT_PATH": str(self.root / "mint-packages"),
                "MINT_LINK_PATH": str(self.root / "mint-links"),
            }
        )

    def tearDown(self):
        self.temporary_directory.cleanup()

    def _write_executable(self, name, content):
        path = self.bin / name
        path.write_text(content, encoding="utf-8")
        path.chmod(0o755)

    def _set_vcs_mode(self, mode):
        for name in (".jj", ".git"):
            path = self.root / name
            if path.exists():
                if path.is_dir():
                    path.rmdir()
                else:
                    path.unlink()
        if mode is not None:
            (self.root / mode).mkdir()

    def _run(self, environment=None):
        return subprocess.run(
            ["/bin/bash", str(self.script)],
            cwd="/",
            env=environment or self.environment,
            text=True,
            capture_output=True,
            check=False,
        )

    def _tool_call_lines(self):
        if not self.calls.exists():
            return []
        return self.calls.read_text(encoding="utf-8").splitlines()

    def _ambient_call_lines(self):
        if not self.ambient_calls.exists():
            return []
        return self.ambient_calls.read_text(encoding="utf-8").splitlines()

    def _clear_logs(self):
        for path in (self.calls, self.ambient_calls, self.vcs_calls):
            path.unlink(missing_ok=True)

    def _assert_no_fake_application(self):
        self.assertEqual(list(self.root.rglob("*.app")), [])
        self.assertEqual(self._ambient_call_lines(), [])

    def test_clean_jj_and_git_only_modes_invoke_exact_pinned_commands(self):
        for mode, vcs_name, vcs_arguments in (
            (".jj", "jj", "diff|--summary"),
            (".git", "git", "status|--porcelain|--untracked-files=all"),
        ):
            with self.subTest(mode=mode):
                self._clear_logs()
                self._set_vcs_mode(mode)

                completed = self._run()

                self.assertEqual(completed.returncode, 0, completed.stderr)
                self.assertEqual(
                    self._tool_call_lines(),
                    [
                        "release-python|run.py|--manifest|generator/manifests/petrel-core.json|--language|swift",
                        "release-mint|run|--executable|swiftformat|nicklockwood/SwiftFormat@0.61.1|Sources/Petrel/Generated",
                    ],
                )
                self.assertEqual(
                    self.vcs_calls.read_text(encoding="utf-8").strip(),
                    f"{vcs_name}|{vcs_arguments}",
                )
                self._assert_no_fake_application()

    def test_dirty_modes_and_vcs_command_failures_reject_before_tools(self):
        for mode, variable in (
            (".jj", "FAKE_JJ_DIRTY"),
            (".git", "FAKE_GIT_DIRTY"),
            (".jj", "FAKE_JJ_FAIL"),
            (".git", "FAKE_GIT_FAIL"),
        ):
            with self.subTest(mode=mode, variable=variable):
                self._clear_logs()
                self._set_vcs_mode(mode)
                environment = dict(self.environment)
                environment[variable] = "1"

                completed = self._run(environment)

                self.assertNotEqual(completed.returncode, 0)
                self.assertEqual(self._tool_call_lines(), [])
                self._assert_no_fake_application()

    def test_missing_environment_and_unsupported_checkout_fail_closed(self):
        self._set_vcs_mode(".jj")
        for variable in (
            "PETREL_PYTHON",
            "RELEASE_MINT",
            "RELEASE_SWIFT",
            "RELEASE_XCODEBUILD",
            "RELEASE_XCRUN",
            "DEVELOPER_DIR",
            "MINT_PATH",
            "MINT_LINK_PATH",
        ):
            with self.subTest(variable=variable):
                self._clear_logs()
                environment = dict(self.environment)
                environment.pop(variable)
                completed = self._run(environment)
                self.assertNotEqual(completed.returncode, 0)
                self.assertEqual(self._tool_call_lines(), [])
                self._assert_no_fake_application()

        self._clear_logs()
        self._set_vcs_mode(None)
        completed = self._run()
        self.assertNotEqual(completed.returncode, 0)
        self.assertEqual(self._tool_call_lines(), [])
        self._assert_no_fake_application()

    def test_colocated_checkout_prefers_jj_mode(self):
        self._set_vcs_mode(".jj")
        (self.root / ".git").mkdir()
        environment = dict(self.environment)
        environment["FAKE_GIT_FAIL"] = "1"

        completed = self._run(environment)

        self.assertEqual(completed.returncode, 0, completed.stderr)
        self.assertEqual(
            self.vcs_calls.read_text(encoding="utf-8").splitlines(),
            ["jj|diff|--summary"],
        )
        self._assert_no_fake_application()

    def test_release_swift_path_mismatch_rejects_without_executing_ambient_tools(self):
        self._set_vcs_mode(".jj")
        environment = dict(self.environment)
        environment["RELEASE_SWIFT"] = str(self.bin / "xcodebuild")

        completed = self._run(environment)

        self.assertNotEqual(completed.returncode, 0)
        self.assertIn("RELEASE_SWIFT is not first on PATH", completed.stderr)
        self.assertEqual(self._tool_call_lines(), [])
        self.assertFalse(self.vcs_calls.exists())
        self._assert_no_fake_application()

    def test_script_has_no_gui_tool_or_application_bundle_escape_hatch(self):
        approved_swift_lookup = "$(command -v swift)"
        self.assertEqual(self.script_text.count(approved_swift_lookup), 1)
        policy_text = self.script_text.replace(
            approved_swift_lookup,
            "approved-release-swift-identity",
        )
        executables = {
            executable
            for line in policy_text.splitlines()
            for executable in command_position_executables(line)
        }
        self.assertTrue(_FORBIDDEN_AMBIENT_EXECUTABLES.isdisjoint(executables))
        self.assertNotIn(".app", self.script_text)
        self.assertNotIn("/Applications", self.script_text)
        self._assert_no_fake_application()

    def test_all_ambient_tool_names_are_fail_and_log_stubs(self):
        for name in sorted(_FORBIDDEN_AMBIENT_EXECUTABLES):
            with self.subTest(name=name):
                stub = self.bin / name
                self.assertTrue(stub.is_file(), f"missing ambient stub for {name}")
                text = stub.read_text(encoding="utf-8")
                self.assertIn("AMBIENT_CALL_LOG", text)
                self.assertIn("exit 97", text)


class WorkflowDeterminismContractTests(unittest.TestCase):
    WORKFLOWS = {
        name: REPOSITORY_ROOT / ".github" / "workflows" / name
        for name in ("generator.yml", "lint.yml", "sync-lexicons.yml")
    }

    @classmethod
    def setUpClass(cls):
        cls.text = {
            name: path.read_text(encoding="utf-8")
            for name, path in cls.WORKFLOWS.items()
        }

    def test_all_macos_release_jobs_use_the_same_verified_stable_tuple_and_bootstrap_order(self):
        ordered_fragments = (
            "actions/setup-python@v5",
            "steps.release-python.outputs.python-path",
            "RELEASE_TOOLCHAIN_LANE=newest-stable",
            "RELEASE_TOOLCHAIN_SELECTION=official-runner-inventory",
            "RELEASE_EVIDENCE_CLASS=stable-release",
            "RELEASE_DEVELOPER_DIR=/Applications/Xcode_26.6.app/Contents/Developer",
            "RELEASE_XCODE_VERSION=26.6",
            "RELEASE_XCODE_BUILD=17F113",
            "source Scripts/activate-release-toolchain.sh",
            'dirname "$RELEASE_SWIFT"',
            '"$GITHUB_PATH"',
            "Scripts/bootstrap-generator-environment.sh",
            "Scripts/verify-generator-environment.sh",
            "Scripts/bootstrap-release-tools.sh",
        )
        for name, text in self.text.items():
            with self.subTest(workflow=name):
                self.assertIn("runs-on: macos-26", text)
                self.assertIn("python-version: '3.12'", text)
                self.assertTrue(has_one_isolated_setup_python_action(text))
                runtime_entries = re.findall(
                    r"^\s*export (RELEASE_(?:IOS|WATCHOS|TVOS|VISIONOS)_RUNTIME)=([^\s]+)$",
                    text,
                    re.MULTILINE,
                )
                self.assertEqual(
                    runtime_entries,
                    [
                        ("RELEASE_IOS_RUNTIME", "26.5"),
                        ("RELEASE_WATCHOS_RUNTIME", "26.5"),
                        ("RELEASE_TVOS_RUNTIME", "26.5"),
                        ("RELEASE_VISIONOS_RUNTIME", "26.5"),
                    ],
                )
                github_path_writes = [
                    line.strip()
                    for line in text.splitlines()
                    if "GITHUB_PATH" in line
                ]
                self.assertEqual(
                    github_path_writes,
                    ['dirname "$RELEASE_SWIFT" >> "$GITHUB_PATH"'],
                )
                positions = []
                for fragment in ordered_fragments:
                    self.assertIn(fragment, text)
                    positions.append(text.index(fragment))
                self.assertEqual(positions, sorted(positions))
                for variable in (
                    "DEVELOPER_DIR",
                    "RELEASE_SWIFT",
                    "RELEASE_XCODEBUILD",
                    "RELEASE_XCRUN",
                ):
                    self.assertRegex(
                        text,
                        rf"{variable}=.*GITHUB_ENV|printf .*{variable}.*GITHUB_ENV",
                    )
                self.assertNotRegex(text.lower(), r"xcode[-_]?beta|local-validation")

    def test_workflows_exclude_ambient_and_homebrew_tool_invocations(self):
        bypass_examples = {
            "env python -m unittest": ("python",),
            "command swift test": ("swift",),
            "/usr/bin/env mint run SwiftFormat": ("mint",),
            "PYTHONPATH=generator python run.py": ("python",),
            "LANE=stable /usr/bin/env PIN=1 command swift --version": ("swift",),
        }
        self.assertEqual(
            {
                example: command_position_executables(example)
                for example in bypass_examples
            },
            bypass_examples,
        )
        for name, text in self.text.items():
            with self.subTest(workflow=name):
                offending = [
                    (line.strip(), executable)
                    for line in workflow_run_lines(text)
                    for executable in workflow_ambient_executables(line)
                ]
                self.assertEqual(offending, [])
                self.assertNotIn("brew install", text)
                self.assertNotIn("pip install", text)

    def test_command_scanner_inspects_every_quote_aware_shell_segment(self):
        cases = {
            "printf '%s' 'safe && python' && env python -V": (
                "printf",
                "python",
            ),
            "command printf ok; command swift --version": (
                "printf",
                "swift",
            ),
            "cat input | LANE='safe; mint' /usr/bin/env PIN=1 mint run": (
                "cat",
                "mint",
            ),
        }
        self.assertEqual(
            {
                line: command_position_executables(line)
                for line in cases
            },
            cases,
        )

    def test_command_scanner_rejects_nested_and_dynamic_ambient_bypasses(self):
        cases = {
            "release_version=$(python -V)": "python",
            "printf '%s\\n' \"$(mint --version)\"": "mint",
            "( swift --version )": "swift",
            "bash -c 'python -V'": "python",
            "eval 'python -V'": "python",
            "env -u PATH python -V": "python",
            "xargs python < list": "python",
            "for x in $(python -V); do :; done": "python",
        }
        for line, forbidden in cases.items():
            with self.subTest(line=line):
                self.assertIn(forbidden, command_position_executables(line))

    def test_workflow_policy_rejects_all_remaining_indirect_ambient_bypasses(self):
        cases = {
            "release_version=`python -V`": "python",
            "env -S 'python -V'": "python",
            "env --split-string='python -V'": "python",
            "env -P /tmp python -V": "python",
            "sudo -u runner python -V": "python",
            "xargs -J % python %": "python",
            "tool=python; \"$tool\" -V": "python",
            "function run { python -V; }; run": "python",
            "nice python -V": "python",
            "nohup python -V": "python",
            "timeout 1 python -V": "python",
            r"find . -exec python -V {} \;": "python",
        }
        for line, forbidden in cases.items():
            with self.subTest(line=line):
                self.assertIn(forbidden, workflow_ambient_executables(line))

        self.assertEqual(workflow_ambient_executables("safe=$((python + 1))"), ())

    def test_workflow_policy_rejects_hidden_dynamic_dispatch(self):
        cases = (
            'tool="$TOOL"; eval "$tool"',
            'bash -c "$SCRIPT"',
            'find . -exec "$TOOL" -V {} \\;',
            'xargs "$TOOL" < list',
            'env "$TOOL" -V',
            "bash -c 'py''thon -V'",
            "eval 'py''thon -V'",
            "env py''thon -V",
            "command py''thon -V",
            'tool=py; tool="${tool}thon"; "$tool" -V',
        )
        for line in cases:
            with self.subTest(line=line):
                self.assertTrue(workflow_ambient_executables(line))

    def test_setup_python_isolation_proof_rejects_a_second_unisolated_action(self):
        marker = "      - uses: actions/setup-python@v5"
        unisolated_step = (
            "      - uses: actions/setup-python@v5\n"
            "        with:\n"
            "          python-version: '3.13'\n"
        )
        for name, text in self.text.items():
            with self.subTest(workflow=name):
                self.assertIn(marker, text)
                mutated = text.replace(marker, unisolated_step + marker, 1)
                self.assertFalse(has_one_isolated_setup_python_action(mutated))

    def test_setup_python_isolation_proof_rejects_misnested_or_wrong_step_keys(self):
        original = (
            "      - uses: actions/setup-python@v5\n"
            "        id: release-python\n"
            "        with:\n"
            "          python-version: '3.12'\n"
            "          update-environment: false\n"
        )
        mutations = (
            (
                "      - uses: actions/setup-python@v5\n"
                "        id: release-python\n"
                "        with:\n"
                "          python-version: '3.12'\n"
                "        env:\n"
                "          update-environment: false\n"
            ),
            original.replace("id: release-python", "id: ambient-python"),
            original.replace("python-version: '3.12'", "python-version: '3.13'"),
        )
        for name, text in self.text.items():
            self.assertIn(original, text, name)
            for mutated_step in mutations:
                with self.subTest(workflow=name, mutation=mutated_step):
                    mutated = text.replace(original, mutated_step, 1)
                    self.assertFalse(has_one_isolated_setup_python_action(mutated))

    def test_generator_runs_tests_then_the_clean_projection_twice_and_checks_all_diff(self):
        text = self.text["generator.yml"]
        tests_command = '"$PETREL_PYTHON" -m unittest discover -s generator/tests -v'
        regenerate_command = "Scripts/regenerate-generated.sh"
        diff_command = "git diff --exit-code -- Sources/Petrel/Generated"
        untracked_command = (
            'test -z "$(git status --porcelain --untracked-files=all -- '
            'Sources/Petrel/Generated)"'
        )
        self.assertEqual(text.count(tests_command), 1)
        regenerate_positions = [
            match.start() for match in re.finditer(re.escape(regenerate_command), text)
        ]
        self.assertEqual(len(regenerate_positions), 2)
        self.assertEqual(text.count(diff_command), 1)
        self.assertEqual(text.count(untracked_command), 1)
        self.assertEqual(
            [
                text.index(tests_command),
                *regenerate_positions,
                text.index(diff_command),
                text.index(untracked_command),
            ],
            sorted(
                [
                    text.index(tests_command),
                    *regenerate_positions,
                    text.index(diff_command),
                    text.index(untracked_command),
                ]
            ),
        )

    def test_lint_uses_only_the_fully_qualified_pinned_mint_command(self):
        text = self.text["lint.yml"]
        self.assertIn(
            '"$RELEASE_MINT" run --executable swiftformat nicklockwood/SwiftFormat@0.61.1',
            text,
        )
        self.assertIn("--lint Sources/Petrel/Generated", text)

    def test_sync_uses_explicit_swift_projection_after_intentional_copy(self):
        text = self.text["sync-lexicons.yml"]
        self.assertNotIn("Scripts/regenerate-generated.sh", text)
        self.assertIn(
            '"$PETREL_PYTHON" run.py',
            text,
        )
        self.assertIn("--manifest generator/manifests/petrel-core.json", text)
        self.assertIn("--language swift", text)
        self.assertIn(
            '"$RELEASE_MINT" run --executable swiftformat nicklockwood/SwiftFormat@0.61.1',
            text,
        )
        self.assertLess(
            text.index("Scripts/bootstrap-release-tools.sh"),
            text.index("rsync -a --delete"),
        )
        lines = text.splitlines()
        add_paths_index = lines.index("          add-paths: |")
        add_paths = []
        for line in lines[add_paths_index + 1:]:
            if not line.startswith("            "):
                break
            add_paths.append(line.strip())
        self.assertEqual(
            add_paths,
            ["generator/lexicons/**", "Sources/Petrel/Generated/**"],
        )


if __name__ == "__main__":
    unittest.main()
