name: Build and Deploy DocC Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10"
        
    - name: Build Documentation
      run: |
        swift package generate-documentation \
          --target Petrel \
          --transform-for-static-hosting \
          --hosting-base-path Petrel \
          --output-path docs-new
          
    - name: Update docs directory
      run: |
        rm -rf docs/*
        cp -r docs-new/* docs/
        rm -rf docs-new
        
    - name: Commit documentation updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        if git diff --staged --quiet; then
          echo "No documentation changes to commit"
        else
          git commit -m "Update DocC documentation

          🤖 Generated with [Claude Code](https://claude.ai/code)
          
          Co-Authored-By: Claude <noreply@anthropic.com>"
          git push
        fi