name: Generate Swift Code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate_swift:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clone external repository
        run: |
          git clone --depth=1 --branch main https://github.com/bluesky-social/atproto.git
          mkdir -p Generator/lexicons
          rsync -a --delete atproto/lexicons/ Generator/lexicons/
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Generator/requirements.txt
      - name: Generate Swift code
        run: |
          python run.py Generator/lexicons Sources/Petrel/Generated
      - name: Install SwiftFormat
        run: |
          brew update
          brew install swiftformat
      - name: Run SwiftFormat
        run: |
          swiftformat .
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update and format generated Swift code"
          
          # Try to push, if it fails due to remote changes, pull and retry once
          if ! git push; then
            echo "Push failed, pulling latest changes and retrying..."
            if git pull --rebase origin main; then
              git push
            else
              echo "Rebase failed due to conflicts. This may require manual intervention."
              git rebase --abort
              echo "Creating a pull request instead would be safer for this case."
              exit 1
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}